--Category----------------------------------------------------
INSERT INTO CATEGORY VALUES (CATEGORY_seq.NEXTVAL,'甜點蛋糕');--1
INSERT INTO CATEGORY VALUES (CATEGORY_seq.NEXTVAL,'餅乾零食');--2
INSERT INTO CATEGORY VALUES (CATEGORY_seq.NEXTVAL,'小吃特產');--3
INSERT INTO CATEGORY VALUES (CATEGORY_seq.NEXTVAL,'蔬果食材');--4
INSERT INTO CATEGORY VALUES (CATEGORY_seq.NEXTVAL,'飲料冰品');--5
INSERT INTO CATEGORY VALUES (CATEGORY_seq.NEXTVAL,'速食料理');--6
INSERT INTO CATEGORY VALUES (CATEGORY_seq.NEXTVAL,'營養保健');--7

--SubCategory----------------------------------------------------
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'蛋糕',1);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'麵包餐包',1);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'麵包餐包',1);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'銅鑼燒',1);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'麻糬大福',1);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'泡芙',1);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'布丁奶酪',1);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'豆花仙草',1);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'瑞士捲奶凍捲',1);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'提拉米蘇',1);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'傳統糕餅',1);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'傳統糕餅',1);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'傳統糕餅',1);

INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'蜜餞果乾',2);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'餅乾',2);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'糖果',2);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'巧克力',2);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'海苔',2);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'瓜子',2);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'花生貢糖',2);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'堅果魚乾',2);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'有機餅乾',2);

INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'滷味',3);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'肉鬆肉乾',3);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'水餃餛飩炒手',3);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'饅頭包子小籠包',3);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'熱狗香腸',3);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'泡菜炒年糕',3);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'地瓜番薯',3);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'粽子油飯',3);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'蔥油餅',3);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'港式糕餅',3);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'傳統小吃',3);

INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'蔬菜',4);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'台灣水果',4);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'進口水果',4);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'水果禮盒',4);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'有機無毒蔬果',4);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'海鮮',4);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'火鍋料',4);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'米飯麵食',4);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'果醬抹醬',4);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'調味品食用油',4);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'烘焙原料',4);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'南北乾貨',4);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'有機無毒食材',4);

INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'茶葉茶包',5);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'咖啡',5);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'牛奶奶粉',5);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'巧克力可可',5);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'麥片穀物',5);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'黑糖',5);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'蜂蜜',5);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'飲用醋果醋',5);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'有機茶飲品',5);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'果汁',5);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'冰品',5);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'餐券',5);

INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'速食調理包',6);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'現烤熟食',6);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'火鍋湯底',6);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'養生雞湯',6);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'豬腳蹄膀',6);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'牛肉麵',6);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'義大利麵',6);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'港式料理',6);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'咖哩料理',6);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'年菜',6);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'罐頭',6);

INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'維他命',7);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'營養補給',7);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'兒童專用',7);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'美顏補給',7);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'養生補給',7);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'體內環保',7);

INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_seq.NEXTVAL,'肉類',4);
--Account----------------------------------------------------
INSERT INTO ACCOUNT (ACC, ACCPW, NICK, EMAIL) VALUES ('root','root','如特','maxdjkl@gmail.com');
INSERT INTO ACCOUNT (ACC, ACCPW, NICK, EMAIL) VALUES ('maxdjkl','maxdjkl','麥克斯','maxdjkl@gmail.com');
INSERT INTO ACCOUNT (ACC, ACCPW, NICK, EMAIL) VALUES ('jimmy','jimmy','吉米','20ahah@gmail.com');
INSERT INTO ACCOUNT (ACC, ACCPW, NICK, EMAIL) VALUES ('killer','killer','齊樂欣','killer740802@hotmail.com');
INSERT INTO ACCOUNT (ACC, ACCPW, NICK, EMAIL) VALUES ('helen','helen','海倫','helenspeaking@gmail.com');
INSERT INTO ACCOUNT (ACC, ACCPW, NICK, EMAIL) VALUES ('alexlee','alexlee','艾力克斯','77ruru@gmail.com');
INSERT INTO ACCOUNT (ACC, ACCPW, NICK, EMAIL) VALUES ('ZouGang','ZouGang','剛諺','zzz9185@hotmail.com');

--Permission----------------------------------------------------
INSERT INTO PERMISSION VALUES (PERMISSION_seq.NEXTVAL,'管理商品分類');
INSERT INTO PERMISSION VALUES (PERMISSION_seq.NEXTVAL,'會員帳號管理');
INSERT INTO PERMISSION VALUES (PERMISSION_seq.NEXTVAL,'商店管理');
INSERT INTO PERMISSION VALUES (PERMISSION_seq.NEXTVAL,'後端帳號管理');
INSERT INTO PERMISSION VALUES (PERMISSION_seq.NEXTVAL,'金流管理');
INSERT INTO PERMISSION VALUES (PERMISSION_seq.NEXTVAL,'首頁管理');
INSERT INTO PERMISSION VALUES (PERMISSION_seq.NEXTVAL,'合購案件管理');
--PerList----------------------------------------------------
INSERT INTO PERLIST VALUES (1,'root');
INSERT INTO PERLIST VALUES (2,'root');
INSERT INTO PERLIST VALUES (3,'root');
INSERT INTO PERLIST VALUES (4,'root');
INSERT INTO PERLIST VALUES (5,'root');
INSERT INTO PERLIST VALUES (6,'root');
INSERT INTO PERLIST VALUES (7,'root');
INSERT INTO PERLIST VALUES (1,'maxdjkl');
INSERT INTO PERLIST VALUES (4,'maxdjkl');
INSERT INTO PERLIST VALUES (7,'jimmy');
INSERT INTO PERLIST VALUES (3,'killer');
INSERT INTO PERLIST VALUES (6,'killer');
INSERT INTO PERLIST VALUES (3,'helen');
INSERT INTO PERLIST VALUES (5,'helen');
INSERT INTO PERLIST VALUES (2,'alexlee');
INSERT INTO PERLIST VALUES (6,'alexlee');


--Location----------------------------------------------------
INSERT INTO LOCATION VALUES (1,'基隆市','仁愛區');
INSERT INTO LOCATION VALUES (2,'基隆市','信義區');
INSERT INTO LOCATION VALUES (3,'基隆市','中正區');
INSERT INTO LOCATION VALUES (4,'基隆市','中山區');
INSERT INTO LOCATION VALUES (5,'基隆市','安樂區');
INSERT INTO LOCATION VALUES (6,'基隆市','暖暖區');
INSERT INTO LOCATION VALUES (7,'基隆市','七堵區');
INSERT INTO LOCATION VALUES (8,'臺北市','中正區');
INSERT INTO LOCATION VALUES (9,'臺北市','大同區');
INSERT INTO LOCATION VALUES (10,'臺北市','中山區');
INSERT INTO LOCATION VALUES (11,'臺北市','松山區');
INSERT INTO LOCATION VALUES (12,'臺北市','大安區');
INSERT INTO LOCATION VALUES (13,'臺北市','萬華區');
INSERT INTO LOCATION VALUES (14,'臺北市','信義區');
INSERT INTO LOCATION VALUES (15,'臺北市','士林區');
INSERT INTO LOCATION VALUES (16,'臺北市','北投區');
INSERT INTO LOCATION VALUES (17,'臺北市','內湖區');
INSERT INTO LOCATION VALUES (18,'臺北市','南港區');
INSERT INTO LOCATION VALUES (19,'臺北市','文山區');
INSERT INTO LOCATION VALUES (20,'新北市','萬里區');
INSERT INTO LOCATION VALUES (21,'新北市','金山區');
INSERT INTO LOCATION VALUES (22,'新北市','板橋區');
INSERT INTO LOCATION VALUES (23,'新北市','汐止區');
INSERT INTO LOCATION VALUES (24,'新北市','深坑區');
INSERT INTO LOCATION VALUES (25,'新北市','石碇區');
INSERT INTO LOCATION VALUES (26,'新北市','瑞芳區');
INSERT INTO LOCATION VALUES (27,'新北市','平溪區');
INSERT INTO LOCATION VALUES (28,'新北市','雙溪區');
INSERT INTO LOCATION VALUES (29,'新北市','貢寮區');
INSERT INTO LOCATION VALUES (30,'新北市','新店區');
INSERT INTO LOCATION VALUES (31,'新北市','坪林區');
INSERT INTO LOCATION VALUES (32,'新北市','烏來區');
INSERT INTO LOCATION VALUES (33,'新北市','永和區');
INSERT INTO LOCATION VALUES (34,'新北市','中和區');
INSERT INTO LOCATION VALUES (35,'新北市','土城區');
INSERT INTO LOCATION VALUES (36,'新北市','三峽區');
INSERT INTO LOCATION VALUES (37,'新北市','樹林區');
INSERT INTO LOCATION VALUES (38,'新北市','鶯歌區');
INSERT INTO LOCATION VALUES (39,'新北市','三重區');
INSERT INTO LOCATION VALUES (40,'新北市','新莊區');
INSERT INTO LOCATION VALUES (41,'新北市','泰山區');
INSERT INTO LOCATION VALUES (42,'新北市','林口區');
INSERT INTO LOCATION VALUES (43,'新北市','蘆洲區');
INSERT INTO LOCATION VALUES (44,'新北市','五股區');
INSERT INTO LOCATION VALUES (45,'新北市','八里區');
INSERT INTO LOCATION VALUES (46,'新北市','淡水區');
INSERT INTO LOCATION VALUES (47,'新北市','三芝區');
INSERT INTO LOCATION VALUES (48,'新北市','石門區');
INSERT INTO LOCATION VALUES (49,'桃園縣','中壢市');
INSERT INTO LOCATION VALUES (50,'桃園縣','平鎮市');
INSERT INTO LOCATION VALUES (51,'桃園縣','龍潭鄉');
INSERT INTO LOCATION VALUES (52,'桃園縣','楊梅市');
INSERT INTO LOCATION VALUES (53,'桃園縣','新屋鄉');
INSERT INTO LOCATION VALUES (54,'桃園縣','觀音鄉');
INSERT INTO LOCATION VALUES (55,'桃園縣','桃園市');
INSERT INTO LOCATION VALUES (56,'桃園縣','龜山鄉');
INSERT INTO LOCATION VALUES (57,'桃園縣','八德市');
INSERT INTO LOCATION VALUES (58,'桃園縣','大溪鎮');
INSERT INTO LOCATION VALUES (59,'桃園縣','復興鄉');
INSERT INTO LOCATION VALUES (60,'桃園縣','大園鄉');
INSERT INTO LOCATION VALUES (61,'桃園縣','蘆竹市');
INSERT INTO LOCATION VALUES (62,'新竹市','東區');
INSERT INTO LOCATION VALUES (63,'新竹市','北區');
INSERT INTO LOCATION VALUES (64,'新竹市','香山區');
INSERT INTO LOCATION VALUES (65,'新竹縣','竹北市');
INSERT INTO LOCATION VALUES (66,'新竹縣','湖口鄉');
INSERT INTO LOCATION VALUES (67,'新竹縣','新豐鄉');
INSERT INTO LOCATION VALUES (68,'新竹縣','新埔鎮');
INSERT INTO LOCATION VALUES (69,'新竹縣','關西鎮');
INSERT INTO LOCATION VALUES (70,'新竹縣','芎林鄉');
INSERT INTO LOCATION VALUES (71,'新竹縣','寶山鄉');
INSERT INTO LOCATION VALUES (72,'新竹縣','竹東鎮');
INSERT INTO LOCATION VALUES (73,'新竹縣','五峰鄉');
INSERT INTO LOCATION VALUES (74,'新竹縣','橫山鄉');
INSERT INTO LOCATION VALUES (75,'新竹縣','尖石鄉');
INSERT INTO LOCATION VALUES (76,'新竹縣','北埔鄉');
INSERT INTO LOCATION VALUES (77,'新竹縣','峨眉鄉');
INSERT INTO LOCATION VALUES (78,'苗栗縣','竹南鎮');
INSERT INTO LOCATION VALUES (79,'苗栗縣','頭份鎮');
INSERT INTO LOCATION VALUES (80,'苗栗縣','三灣鄉');
INSERT INTO LOCATION VALUES (81,'苗栗縣','南庄鄉');
INSERT INTO LOCATION VALUES (82,'苗栗縣','獅潭鄉');
INSERT INTO LOCATION VALUES (83,'苗栗縣','後龍鎮');
INSERT INTO LOCATION VALUES (84,'苗栗縣','通霄鎮');
INSERT INTO LOCATION VALUES (85,'苗栗縣','苑裡鎮');
INSERT INTO LOCATION VALUES (86,'苗栗縣','苗栗市');
INSERT INTO LOCATION VALUES (87,'苗栗縣','造橋鄉');
INSERT INTO LOCATION VALUES (88,'苗栗縣','頭屋鄉');
INSERT INTO LOCATION VALUES (89,'苗栗縣','公館鄉');
INSERT INTO LOCATION VALUES (90,'苗栗縣','大湖鄉');
INSERT INTO LOCATION VALUES (91,'苗栗縣','泰安鄉');
INSERT INTO LOCATION VALUES (92,'苗栗縣','銅鑼鄉');
INSERT INTO LOCATION VALUES (93,'苗栗縣','三義鄉');
INSERT INTO LOCATION VALUES (94,'苗栗縣','西湖鄉');
INSERT INTO LOCATION VALUES (95,'苗栗縣','卓蘭鎮');
INSERT INTO LOCATION VALUES (96,'臺中市','中區');
INSERT INTO LOCATION VALUES (97,'臺中市','東區');
INSERT INTO LOCATION VALUES (98,'臺中市','南區');
INSERT INTO LOCATION VALUES (99,'臺中市','西區');
INSERT INTO LOCATION VALUES (100,'臺中市','北區');
INSERT INTO LOCATION VALUES (101,'臺中市','北屯區');
INSERT INTO LOCATION VALUES (102,'臺中市','西屯區');
INSERT INTO LOCATION VALUES (103,'臺中市','南屯區');
INSERT INTO LOCATION VALUES (104,'臺中市','太平區');
INSERT INTO LOCATION VALUES (105,'臺中市','大里區');
INSERT INTO LOCATION VALUES (106,'臺中市','霧峰區');
INSERT INTO LOCATION VALUES (107,'臺中市','烏日區');
INSERT INTO LOCATION VALUES (108,'臺中市','豐原區');
INSERT INTO LOCATION VALUES (109,'臺中市','后里區');
INSERT INTO LOCATION VALUES (110,'臺中市','石岡區');
INSERT INTO LOCATION VALUES (111,'臺中市','東勢區');
INSERT INTO LOCATION VALUES (112,'臺中市','和平區');
INSERT INTO LOCATION VALUES (113,'臺中市','新社區');
INSERT INTO LOCATION VALUES (114,'臺中市','潭子區');
INSERT INTO LOCATION VALUES (115,'臺中市','大雅區');
INSERT INTO LOCATION VALUES (116,'臺中市','神岡區');
INSERT INTO LOCATION VALUES (117,'臺中市','大肚區');
INSERT INTO LOCATION VALUES (118,'臺中市','沙鹿區');
INSERT INTO LOCATION VALUES (119,'臺中市','龍井區');
INSERT INTO LOCATION VALUES (120,'臺中市','梧棲區');
INSERT INTO LOCATION VALUES (121,'臺中市','清水區');
INSERT INTO LOCATION VALUES (122,'臺中市','大甲區');
INSERT INTO LOCATION VALUES (123,'臺中市','外埔區');
INSERT INTO LOCATION VALUES (124,'臺中市','大安區');
INSERT INTO LOCATION VALUES (125,'彰化縣','彰化市');
INSERT INTO LOCATION VALUES (126,'彰化縣','芬園鄉');
INSERT INTO LOCATION VALUES (127,'彰化縣','花壇鄉');
INSERT INTO LOCATION VALUES (128,'彰化縣','秀水鄉');
INSERT INTO LOCATION VALUES (129,'彰化縣','鹿港鎮');
INSERT INTO LOCATION VALUES (130,'彰化縣','福興鄉');
INSERT INTO LOCATION VALUES (131,'彰化縣','線西鄉');
INSERT INTO LOCATION VALUES (132,'彰化縣','和美鎮');
INSERT INTO LOCATION VALUES (133,'彰化縣','伸港鄉');
INSERT INTO LOCATION VALUES (134,'彰化縣','員林鎮');
INSERT INTO LOCATION VALUES (135,'彰化縣','社頭鄉');
INSERT INTO LOCATION VALUES (136,'彰化縣','永靖鄉');
INSERT INTO LOCATION VALUES (137,'彰化縣','埔心鄉');
INSERT INTO LOCATION VALUES (138,'彰化縣','溪湖鎮');
INSERT INTO LOCATION VALUES (139,'彰化縣','大村鄉');
INSERT INTO LOCATION VALUES (140,'彰化縣','埔鹽鄉');
INSERT INTO LOCATION VALUES (141,'彰化縣','田中鎮');
INSERT INTO LOCATION VALUES (142,'彰化縣','北斗鎮');
INSERT INTO LOCATION VALUES (143,'彰化縣','田尾鄉');
INSERT INTO LOCATION VALUES (144,'彰化縣','埤頭鄉');
INSERT INTO LOCATION VALUES (145,'彰化縣','溪州鄉');
INSERT INTO LOCATION VALUES (146,'彰化縣','竹塘鄉');
INSERT INTO LOCATION VALUES (147,'彰化縣','二林鎮');
INSERT INTO LOCATION VALUES (148,'彰化縣','大城鄉');
INSERT INTO LOCATION VALUES (149,'彰化縣','芳苑鄉');
INSERT INTO LOCATION VALUES (150,'彰化縣','二水鄉');
INSERT INTO LOCATION VALUES (151,'南投縣','南投市');
INSERT INTO LOCATION VALUES (152,'南投縣','中寮鄉');
INSERT INTO LOCATION VALUES (153,'南投縣','草屯鎮');
INSERT INTO LOCATION VALUES (154,'南投縣','國姓鄉');
INSERT INTO LOCATION VALUES (155,'南投縣','埔里鎮');
INSERT INTO LOCATION VALUES (156,'南投縣','仁愛鄉');
INSERT INTO LOCATION VALUES (157,'南投縣','名間鄉');
INSERT INTO LOCATION VALUES (158,'南投縣','集集鎮');
INSERT INTO LOCATION VALUES (159,'南投縣','水里鄉');
INSERT INTO LOCATION VALUES (160,'南投縣','魚池鄉');
INSERT INTO LOCATION VALUES (161,'南投縣','信義鄉');
INSERT INTO LOCATION VALUES (162,'南投縣','竹山鎮');
INSERT INTO LOCATION VALUES (163,'南投縣','鹿谷鄉');
INSERT INTO LOCATION VALUES (164,'雲林縣','斗南鎮');
INSERT INTO LOCATION VALUES (165,'雲林縣','大埤鄉');
INSERT INTO LOCATION VALUES (166,'雲林縣','虎尾鎮');
INSERT INTO LOCATION VALUES (167,'雲林縣','土庫鎮');
INSERT INTO LOCATION VALUES (168,'雲林縣','褒忠鄉');
INSERT INTO LOCATION VALUES (169,'雲林縣','東勢鄉');
INSERT INTO LOCATION VALUES (170,'雲林縣','臺西鄉');
INSERT INTO LOCATION VALUES (171,'雲林縣','崙背鄉');
INSERT INTO LOCATION VALUES (172,'雲林縣','麥寮鄉');
INSERT INTO LOCATION VALUES (173,'雲林縣','斗六市');
INSERT INTO LOCATION VALUES (174,'雲林縣','林內鄉');
INSERT INTO LOCATION VALUES (175,'雲林縣','古坑鄉');
INSERT INTO LOCATION VALUES (176,'雲林縣','莿桐鄉');
INSERT INTO LOCATION VALUES (177,'雲林縣','西螺鎮');
INSERT INTO LOCATION VALUES (178,'雲林縣','二崙鄉');
INSERT INTO LOCATION VALUES (179,'雲林縣','北港鎮');
INSERT INTO LOCATION VALUES (180,'雲林縣','水林鄉');
INSERT INTO LOCATION VALUES (181,'雲林縣','口湖鄉');
INSERT INTO LOCATION VALUES (182,'雲林縣','四湖鄉');
INSERT INTO LOCATION VALUES (183,'雲林縣','元長鄉');
INSERT INTO LOCATION VALUES (184,'嘉義市','東區');
INSERT INTO LOCATION VALUES (185,'嘉義市','西區');
INSERT INTO LOCATION VALUES (186,'嘉義縣','番路鄉');
INSERT INTO LOCATION VALUES (187,'嘉義縣','梅山鄉');
INSERT INTO LOCATION VALUES (188,'嘉義縣','竹崎鄉');
INSERT INTO LOCATION VALUES (189,'嘉義縣','阿里山鄉');
INSERT INTO LOCATION VALUES (190,'嘉義縣','中埔鄉');
INSERT INTO LOCATION VALUES (191,'嘉義縣','大埔鄉');
INSERT INTO LOCATION VALUES (192,'嘉義縣','水上鄉');
INSERT INTO LOCATION VALUES (193,'嘉義縣','鹿草鄉');
INSERT INTO LOCATION VALUES (194,'嘉義縣','太保市');
INSERT INTO LOCATION VALUES (195,'嘉義縣','朴子市');
INSERT INTO LOCATION VALUES (196,'嘉義縣','東石鄉');
INSERT INTO LOCATION VALUES (197,'嘉義縣','六腳鄉');
INSERT INTO LOCATION VALUES (198,'嘉義縣','新港鄉');
INSERT INTO LOCATION VALUES (199,'嘉義縣','民雄鄉');
INSERT INTO LOCATION VALUES (200,'嘉義縣','大林鎮');
INSERT INTO LOCATION VALUES (201,'嘉義縣','溪口鄉');
INSERT INTO LOCATION VALUES (202,'嘉義縣','義竹鄉');
INSERT INTO LOCATION VALUES (203,'嘉義縣','布袋鎮');
INSERT INTO LOCATION VALUES (204,'臺南市','中西區');
INSERT INTO LOCATION VALUES (205,'臺南市','東區');
INSERT INTO LOCATION VALUES (206,'臺南市','南區');
INSERT INTO LOCATION VALUES (207,'臺南市','北區');
INSERT INTO LOCATION VALUES (208,'臺南市','安平區');
INSERT INTO LOCATION VALUES (209,'臺南市','安南區');
INSERT INTO LOCATION VALUES (210,'臺南市','永康區');
INSERT INTO LOCATION VALUES (211,'臺南市','歸仁區');
INSERT INTO LOCATION VALUES (212,'臺南市','新化區');
INSERT INTO LOCATION VALUES (213,'臺南市','左鎮區');
INSERT INTO LOCATION VALUES (214,'臺南市','玉井區');
INSERT INTO LOCATION VALUES (215,'臺南市','楠西區');
INSERT INTO LOCATION VALUES (216,'臺南市','南化區');
INSERT INTO LOCATION VALUES (217,'臺南市','仁德區');
INSERT INTO LOCATION VALUES (218,'臺南市','關廟區');
INSERT INTO LOCATION VALUES (219,'臺南市','龍崎區');
INSERT INTO LOCATION VALUES (220,'臺南市','官田區');
INSERT INTO LOCATION VALUES (221,'臺南市','麻豆區');
INSERT INTO LOCATION VALUES (222,'臺南市','佳里區');
INSERT INTO LOCATION VALUES (223,'臺南市','西港區');
INSERT INTO LOCATION VALUES (224,'臺南市','七股區');
INSERT INTO LOCATION VALUES (225,'臺南市','將軍區');
INSERT INTO LOCATION VALUES (226,'臺南市','學甲區');
INSERT INTO LOCATION VALUES (227,'臺南市','北門區');
INSERT INTO LOCATION VALUES (228,'臺南市','新營區');
INSERT INTO LOCATION VALUES (229,'臺南市','後壁區');
INSERT INTO LOCATION VALUES (230,'臺南市','白河區');
INSERT INTO LOCATION VALUES (231,'臺南市','東山區');
INSERT INTO LOCATION VALUES (232,'臺南市','六甲區');
INSERT INTO LOCATION VALUES (233,'臺南市','下營區');
INSERT INTO LOCATION VALUES (234,'臺南市','柳營區');
INSERT INTO LOCATION VALUES (235,'臺南市','鹽水區');
INSERT INTO LOCATION VALUES (236,'臺南市','善化區');
INSERT INTO LOCATION VALUES (237,'臺南市','大內區');
INSERT INTO LOCATION VALUES (238,'臺南市','山上區');
INSERT INTO LOCATION VALUES (239,'臺南市','新市區');
INSERT INTO LOCATION VALUES (240,'臺南市','安定區');
INSERT INTO LOCATION VALUES (241,'高雄市','新興區');
INSERT INTO LOCATION VALUES (242,'高雄市','前金區');
INSERT INTO LOCATION VALUES (243,'高雄市','苓雅區');
INSERT INTO LOCATION VALUES (244,'高雄市','鹽埕區');
INSERT INTO LOCATION VALUES (245,'高雄市','鼓山區');
INSERT INTO LOCATION VALUES (246,'高雄市','旗津區');
INSERT INTO LOCATION VALUES (247,'高雄市','前鎮區');
INSERT INTO LOCATION VALUES (248,'高雄市','三民區');
INSERT INTO LOCATION VALUES (249,'高雄市','楠梓區');
INSERT INTO LOCATION VALUES (250,'高雄市','小港區');
INSERT INTO LOCATION VALUES (251,'高雄市','左營區');
INSERT INTO LOCATION VALUES (252,'高雄市','仁武區');
INSERT INTO LOCATION VALUES (253,'高雄市','大社區');
INSERT INTO LOCATION VALUES (254,'高雄市','東沙群島');
INSERT INTO LOCATION VALUES (255,'高雄市','南沙群島');
INSERT INTO LOCATION VALUES (256,'高雄市','岡山區');
INSERT INTO LOCATION VALUES (257,'高雄市','路竹區');
INSERT INTO LOCATION VALUES (258,'高雄市','阿蓮區');
INSERT INTO LOCATION VALUES (259,'高雄市','田寮區');
INSERT INTO LOCATION VALUES (260,'高雄市','燕巢區');
INSERT INTO LOCATION VALUES (261,'高雄市','橋頭區');
INSERT INTO LOCATION VALUES (262,'高雄市','梓官區');
INSERT INTO LOCATION VALUES (263,'高雄市','彌陀區');
INSERT INTO LOCATION VALUES (264,'高雄市','永安區');
INSERT INTO LOCATION VALUES (265,'高雄市','湖內區');
INSERT INTO LOCATION VALUES (266,'高雄市','鳳山區');
INSERT INTO LOCATION VALUES (267,'高雄市','大寮區');
INSERT INTO LOCATION VALUES (268,'高雄市','林園區');
INSERT INTO LOCATION VALUES (269,'高雄市','鳥松區');
INSERT INTO LOCATION VALUES (270,'高雄市','大樹區');
INSERT INTO LOCATION VALUES (271,'高雄市','旗山區');
INSERT INTO LOCATION VALUES (272,'高雄市','美濃區');
INSERT INTO LOCATION VALUES (273,'高雄市','六龜區');
INSERT INTO LOCATION VALUES (274,'高雄市','內門區');
INSERT INTO LOCATION VALUES (275,'高雄市','杉林區');
INSERT INTO LOCATION VALUES (276,'高雄市','甲仙區');
INSERT INTO LOCATION VALUES (277,'高雄市','桃源區');
INSERT INTO LOCATION VALUES (278,'高雄市','那瑪夏區');
INSERT INTO LOCATION VALUES (279,'高雄市','茂林區');
INSERT INTO LOCATION VALUES (280,'高雄市','茄萣區');
INSERT INTO LOCATION VALUES (281,'屏東縣','屏東市');
INSERT INTO LOCATION VALUES (282,'屏東縣','三地門鄉');
INSERT INTO LOCATION VALUES (283,'屏東縣','霧臺鄉');
INSERT INTO LOCATION VALUES (284,'屏東縣','瑪家鄉');
INSERT INTO LOCATION VALUES (285,'屏東縣','九如鄉');
INSERT INTO LOCATION VALUES (286,'屏東縣','里港鄉');
INSERT INTO LOCATION VALUES (287,'屏東縣','高樹鄉');
INSERT INTO LOCATION VALUES (288,'屏東縣','鹽埔鄉');
INSERT INTO LOCATION VALUES (289,'屏東縣','長治鄉');
INSERT INTO LOCATION VALUES (290,'屏東縣','麟洛鄉');
INSERT INTO LOCATION VALUES (291,'屏東縣','竹田鄉');
INSERT INTO LOCATION VALUES (292,'屏東縣','內埔鄉');
INSERT INTO LOCATION VALUES (293,'屏東縣','萬丹鄉');
INSERT INTO LOCATION VALUES (294,'屏東縣','潮州鎮');
INSERT INTO LOCATION VALUES (295,'屏東縣','泰武鄉');
INSERT INTO LOCATION VALUES (296,'屏東縣','來義鄉');
INSERT INTO LOCATION VALUES (297,'屏東縣','萬巒鄉');
INSERT INTO LOCATION VALUES (298,'屏東縣','崁頂鄉');
INSERT INTO LOCATION VALUES (299,'屏東縣','新埤鄉');
INSERT INTO LOCATION VALUES (300,'屏東縣','南州鄉');
INSERT INTO LOCATION VALUES (301,'屏東縣','林邊鄉');
INSERT INTO LOCATION VALUES (302,'屏東縣','東港鎮');
INSERT INTO LOCATION VALUES (303,'屏東縣','琉球鄉');
INSERT INTO LOCATION VALUES (304,'屏東縣','佳冬鄉');
INSERT INTO LOCATION VALUES (305,'屏東縣','新園鄉');
INSERT INTO LOCATION VALUES (306,'屏東縣','枋寮鄉');
INSERT INTO LOCATION VALUES (307,'屏東縣','枋山鄉');
INSERT INTO LOCATION VALUES (308,'屏東縣','春日鄉');
INSERT INTO LOCATION VALUES (309,'屏東縣','獅子鄉');
INSERT INTO LOCATION VALUES (310,'屏東縣','車城鄉');
INSERT INTO LOCATION VALUES (311,'屏東縣','牡丹鄉');
INSERT INTO LOCATION VALUES (312,'屏東縣','恆春鎮');
INSERT INTO LOCATION VALUES (313,'屏東縣','滿州鄉');
INSERT INTO LOCATION VALUES (314,'臺東縣','臺東市');
INSERT INTO LOCATION VALUES (315,'臺東縣','綠島鄉');
INSERT INTO LOCATION VALUES (316,'臺東縣','蘭嶼鄉');
INSERT INTO LOCATION VALUES (317,'臺東縣','延平鄉');
INSERT INTO LOCATION VALUES (318,'臺東縣','卑南鄉');
INSERT INTO LOCATION VALUES (319,'臺東縣','鹿野鄉');
INSERT INTO LOCATION VALUES (320,'臺東縣','關山鎮');
INSERT INTO LOCATION VALUES (321,'臺東縣','海端鄉');
INSERT INTO LOCATION VALUES (322,'臺東縣','池上鄉');
INSERT INTO LOCATION VALUES (323,'臺東縣','東河鄉');
INSERT INTO LOCATION VALUES (324,'臺東縣','成功鎮');
INSERT INTO LOCATION VALUES (325,'臺東縣','長濱鄉');
INSERT INTO LOCATION VALUES (326,'臺東縣','太麻里鄉');
INSERT INTO LOCATION VALUES (327,'臺東縣','金峰鄉');
INSERT INTO LOCATION VALUES (328,'臺東縣','大武鄉');
INSERT INTO LOCATION VALUES (329,'臺東縣','達仁鄉');
INSERT INTO LOCATION VALUES (330,'花蓮縣','花蓮市');
INSERT INTO LOCATION VALUES (331,'花蓮縣','新城鄉');
INSERT INTO LOCATION VALUES (332,'花蓮縣','秀林鄉');
INSERT INTO LOCATION VALUES (333,'花蓮縣','吉安鄉');
INSERT INTO LOCATION VALUES (334,'花蓮縣','壽豐鄉');
INSERT INTO LOCATION VALUES (335,'花蓮縣','鳳林鎮');
INSERT INTO LOCATION VALUES (336,'花蓮縣','光復鄉');
INSERT INTO LOCATION VALUES (337,'花蓮縣','豐濱鄉');
INSERT INTO LOCATION VALUES (338,'花蓮縣','瑞穗鄉');
INSERT INTO LOCATION VALUES (339,'花蓮縣','萬榮鄉');
INSERT INTO LOCATION VALUES (340,'花蓮縣','玉里鎮');
INSERT INTO LOCATION VALUES (341,'花蓮縣','卓溪鄉');
INSERT INTO LOCATION VALUES (342,'花蓮縣','富里鄉');
INSERT INTO LOCATION VALUES (343,'宜蘭縣','宜蘭市');
INSERT INTO LOCATION VALUES (344,'宜蘭縣','頭城鎮');
INSERT INTO LOCATION VALUES (345,'宜蘭縣','礁溪鄉');
INSERT INTO LOCATION VALUES (346,'宜蘭縣','壯圍鄉');
INSERT INTO LOCATION VALUES (347,'宜蘭縣','員山鄉');
INSERT INTO LOCATION VALUES (348,'宜蘭縣','羅東鎮');
INSERT INTO LOCATION VALUES (349,'宜蘭縣','三星鄉');
INSERT INTO LOCATION VALUES (350,'宜蘭縣','大同鄉');
INSERT INTO LOCATION VALUES (351,'宜蘭縣','五結鄉');
INSERT INTO LOCATION VALUES (352,'宜蘭縣','冬山鄉');
INSERT INTO LOCATION VALUES (353,'宜蘭縣','蘇澳鎮');
INSERT INTO LOCATION VALUES (354,'宜蘭縣','南澳鄉');
INSERT INTO LOCATION VALUES (355,'宜蘭縣','釣魚台');

--Member-----------------------------------------------------------------
/*Normal Member Below*/
--/*1*/INSERT INTO MEMBER VALUES (member_seq.NEXTVAL,'apple','apple','蘋果','李', 'A123456789', 'F', '50', '桃園縣中壢市環西路一段1號1樓', '0988123456', 'apple@gmail.com', null, null, 0, 0, 0, 0, 0, 0);
--/*2*/INSERT INTO MEMBER VALUES (member_seq.NEXTVAL,'bird','bird','博得','錢', 'B123456789', 'M', '50', '桃園縣中壢市中正路95號', '0933123456', 'bird@gmail.com', null, null, 0, 0, 0, 0, 0, 0);
--/*3*/INSERT INTO MEMBER VALUES (member_seq.NEXTVAL,'doggy','doggy','都格','王', 'D123456789', 'M', '22', '新北市板橋區中山路一段104號1樓', '0911123456', 'doggy@gmail.com', null, null, 0, 0, 0, 0, 0, 0);
--/*4*/INSERT INTO MEMBER VALUES (member_seq.NEXTVAL,'egg','egg','艾格','陳', 'E123456789', 'M', '43', '新北市蘆洲區長安街68巷31號2樓', '0944123456', 'egg@gmail.com', null, null, 0, 0, 0, 0, 0, 0);
--/*5*/INSERT INTO MEMBER VALUES (member_seq.NEXTVAL,'fox','fox','福斯','林', 'F123456789', 'M', '13', '台北市萬華區和平西路三段382巷6號5樓', '0955123456', 'fox@gmail.com', null, null, 0, 0, 0, 0, 0, 0);
--/*6*/INSERT INTO MEMBER VALUES (member_seq.NEXTVAL,'girl','girl','閣樓','鄭', 'G123456789', 'F', '34', '新北市中和區莒光路129巷2弄1號', '0966123456', 'girl@gmail.com', null, null, 0, 0, 0, 0, 0, 0);
--/*7*/INSERT INTO MEMBER VALUES (member_seq.NEXTVAL,'ham','ham','哈姆','包', 'H123456789', 'M', '50', '桃園縣中壢市環北路一段33號7樓', '0977123456', 'ham@gmail.com', null, null, 0, 0, 0, 0, 0, 0);
--/*8*/INSERT INTO MEMBER VALUES (member_seq.NEXTVAL,'ice','ice','愛絲','彭', 'I123456789', 'F', '22', '新北市板橋區中山路一段102號2樓', '0988193456', 'ice@gmail.com', null, null, 0, 0, 0, 0, 0, 0);
--/*9*/INSERT INTO MEMBER VALUES (member_seq.NEXTVAL,'jack','jack','捷克','劉', 'J123456789', 'M', '50', '桃園縣中壢市中正路115號', '0988113456', 'jack@gmail.com', null, null, 0, 0, 0, 0, 0, 0);
--/*10*/INSERT INTO MEMBER VALUES (member_seq.NEXTVAL,'king','king','肯恩','郭', 'K123456789', 'M', '34', '新北市中和區莒光路125巷3弄2號', '0988121456', 'king@gmail.com', null, null, 0, 0, 0, 0, 0, 0);
--/*11*/INSERT INTO MEMBER VALUES (member_seq.NEXTVAL,'lemon','lemon','雷猛','黎', 'L123456789', 'M', '17', '台北市內湖區內湖路二段2號5樓', '0988123156', 'lemon@gmail.com', null, null, 0, 0, 0, 0, 0, 0);
--/*12*/INSERT INTO MEMBER VALUES (member_seq.NEXTVAL,'monkey','monkey','芒克','金', 'M123456789', 'M', '50', '桃園縣中壢市中山路11號', '0988123416', 'monkey@gmail.com', null, null, 0, 0, 0, 0, 0, 0);
/*Shop Member Below*/
--/*13*/INSERT INTO MEMBER VALUES (member_seq.NEXTVAL,'nose','nose','娜絲','武', 'N123456789', 'F', '22', '新北市板橋區中山路二段104號5樓', '0988123451', 'nose@gmail.com', null, null, 0, 0, 0, 0, 1, 0);
--/*14*/INSERT INTO MEMBER VALUES (member_seq.NEXTVAL,'piggy','piggy','佩姬','潘', 'P123456789', 'F', '43', '新北市蘆洲區長安街68巷31號3樓', '0981123456', 'piggy@gmail.com', null, null, 0, 0, 0, 0, 1, 0);
--/*15*/INSERT INTO MEMBER VALUES (member_seq.NEXTVAL,'queen','queen','昆恩','謝', 'Q123456789', 'F', '34', '新北市中和區莒光路119巷2弄2號', '0918123456', 'queen@gmail.com', null, null, 0, 0, 0, 0, 1, 0);
--/*16*/INSERT INTO MEMBER VALUES (member_seq.NEXTVAL,'rabbit','rabbit','拉貝','吳', 'R123456789', 'F', '17', '台北市內湖區內湖路二段3號1樓', '0982123456', 'rabbit@gmail.com', null, null, 0, 0, 0, 0, 1, 0);
--/*17*/INSERT INTO MEMBER VALUES (member_seq.NEXTVAL,'super','super','速博','齊', 'S123456789', 'M', '43', '新北市蘆洲區長安街68巷33號5樓', '0988223456', 'super@gmail.com', null, null, 0, 0, 0, 0, 1, 0);
--/*18*/INSERT INTO MEMBER VALUES (member_seq.NEXTVAL,'tea','tea','提兒','余', 'T123456789', 'F', '22', '新北市板橋區中山路一段10號3樓', '0988122456', 'tea@gmail.com', null, null, 0, 0, 0, 0, 1, 0);
Insert into YA803G2.MEMBER (MEMNO,MEMID,MEMPW,FNAME,LNAME,IDNUM,GENDER,LOCNO,ADDR,TEL,EMAIL,MIME,POINT,MONEY,ADDAYS,STATUS,TYPE,WITHHOLD) values (member_seq.NEXTVAL,'apple','apple','蘋果','李','A123456789','F',50,'桃園縣中壢市環西路一段1號1樓','0988123456','apple@gmail.com','image/png',8,12043,0,1,0,157);
Insert into YA803G2.MEMBER (MEMNO,MEMID,MEMPW,FNAME,LNAME,IDNUM,GENDER,LOCNO,ADDR,TEL,EMAIL,MIME,POINT,MONEY,ADDAYS,STATUS,TYPE,WITHHOLD) values (member_seq.NEXTVAL,'bird','bird','博得','錢','B123456789','M',50,'桃園縣中壢市中正路95號','0933123456','bird@gmail.com','image/png',2,8785,0,1,0,765);
Insert into YA803G2.MEMBER (MEMNO,MEMID,MEMPW,FNAME,LNAME,IDNUM,GENDER,LOCNO,ADDR,TEL,EMAIL,MIME,POINT,MONEY,ADDAYS,STATUS,TYPE,WITHHOLD) values (member_seq.NEXTVAL,'doggy','doggy','都格','王','D123456789','M',22,'新北市板橋區中山路一段104號1樓','0911123456','doggy@gmail.com','image/png',10,8414,0,1,0,461);
Insert into YA803G2.MEMBER (MEMNO,MEMID,MEMPW,FNAME,LNAME,IDNUM,GENDER,LOCNO,ADDR,TEL,EMAIL,MIME,POINT,MONEY,ADDAYS,STATUS,TYPE,WITHHOLD) values (member_seq.NEXTVAL,'egg','egg','艾格','陳','E123456789','M',43,'新北市蘆洲區長安街68巷31號2樓','0944123456','egg@gmail.com','image/png',4,8718,0,1,0,157);
Insert into YA803G2.MEMBER (MEMNO,MEMID,MEMPW,FNAME,LNAME,IDNUM,GENDER,LOCNO,ADDR,TEL,EMAIL,MIME,POINT,MONEY,ADDAYS,STATUS,TYPE,WITHHOLD) values (member_seq.NEXTVAL,'fox','fox','福斯','林','F123456789','M',13,'台北市萬華區和平西路三段382巷6號5樓','0955123456','fox@gmail.com','image/png',2,9539,0,1,0,461);
Insert into YA803G2.MEMBER (MEMNO,MEMID,MEMPW,FNAME,LNAME,IDNUM,GENDER,LOCNO,ADDR,TEL,EMAIL,MIME,POINT,MONEY,ADDAYS,STATUS,TYPE,WITHHOLD) values (member_seq.NEXTVAL,'girl','girl','閣樓','鄭','G123456789','F',34,'新北市中和區莒光路129巷2弄1號','0966123456','girl@gmail.com','image/png',2,10000,0,1,0,0);
Insert into YA803G2.MEMBER (MEMNO,MEMID,MEMPW,FNAME,LNAME,IDNUM,GENDER,LOCNO,ADDR,TEL,EMAIL,MIME,POINT,MONEY,ADDAYS,STATUS,TYPE,WITHHOLD) values (member_seq.NEXTVAL,'ham','ham','哈姆','包','H123456789','M',50,'桃園縣中壢市環北路一段33號7樓','0977123456','ham@gmail.com','image/png',2,10000,0,1,0,0);
Insert into YA803G2.MEMBER (MEMNO,MEMID,MEMPW,FNAME,LNAME,IDNUM,GENDER,LOCNO,ADDR,TEL,EMAIL,MIME,POINT,MONEY,ADDAYS,STATUS,TYPE,WITHHOLD) values (member_seq.NEXTVAL,'ice','ice','愛絲','彭','I123456789','F',22,'新北市板橋區中山路一段102號2樓','0988193456','ice@gmail.com','image/png',0,10000,0,1,0,0);
Insert into YA803G2.MEMBER (MEMNO,MEMID,MEMPW,FNAME,LNAME,IDNUM,GENDER,LOCNO,ADDR,TEL,EMAIL,MIME,POINT,MONEY,ADDAYS,STATUS,TYPE,WITHHOLD) values (member_seq.NEXTVAL,'jack','jack','捷克','劉','J123456789','M',50,'桃園縣中壢市中正路115號','0988113456','jack@gmail.com','image/png',0,10000,0,1,0,0);
Insert into YA803G2.MEMBER (MEMNO,MEMID,MEMPW,FNAME,LNAME,IDNUM,GENDER,LOCNO,ADDR,TEL,EMAIL,MIME,POINT,MONEY,ADDAYS,STATUS,TYPE,WITHHOLD) values (member_seq.NEXTVAL,'king','king','肯恩','郭','K123456789','M',34,'新北市中和區莒光路125巷3弄2號','0988121456','king@gmail.com','image/png',0,10000,0,1,0,0);
Insert into YA803G2.MEMBER (MEMNO,MEMID,MEMPW,FNAME,LNAME,IDNUM,GENDER,LOCNO,ADDR,TEL,EMAIL,MIME,POINT,MONEY,ADDAYS,STATUS,TYPE,WITHHOLD) values (member_seq.NEXTVAL,'lemon','lemon','雷猛','黎','L123456789','M',17,'台北市內湖區內湖路二段2號5樓','0988123156','lemon@gmail.com','image/png',0,10000,0,1,0,0);
Insert into YA803G2.MEMBER (MEMNO,MEMID,MEMPW,FNAME,LNAME,IDNUM,GENDER,LOCNO,ADDR,TEL,EMAIL,MIME,POINT,MONEY,ADDAYS,STATUS,TYPE,WITHHOLD) values (member_seq.NEXTVAL,'monkey','monkey','芒克','金','M123456789','M',50,'桃園縣中壢市中山路11號','0988123416','monkey@gmail.com','image/png',0,10000,0,1,0,0);
Insert into YA803G2.MEMBER (MEMNO,MEMID,MEMPW,FNAME,LNAME,IDNUM,GENDER,LOCNO,ADDR,TEL,EMAIL,MIME,POINT,MONEY,ADDAYS,STATUS,TYPE,WITHHOLD) values (member_seq.NEXTVAL,'nose','nose','娜絲','武','N123456789','F',22,'新北市板橋區中山路二段104號5樓','0988123451','nose@gmail.com','image/png',5,10000,0,1,1,0);
Insert into YA803G2.MEMBER (MEMNO,MEMID,MEMPW,FNAME,LNAME,IDNUM,GENDER,LOCNO,ADDR,TEL,EMAIL,MIME,POINT,MONEY,ADDAYS,STATUS,TYPE,WITHHOLD) values (member_seq.NEXTVAL,'piggy','piggy','佩姬','潘','P123456789','F',43,'新北市蘆洲區長安街68巷31號3樓','0981123456','piggy@gmail.com','image/png',0,10000,0,1,1,0);
Insert into YA803G2.MEMBER (MEMNO,MEMID,MEMPW,FNAME,LNAME,IDNUM,GENDER,LOCNO,ADDR,TEL,EMAIL,MIME,POINT,MONEY,ADDAYS,STATUS,TYPE,WITHHOLD) values (member_seq.NEXTVAL,'queen','queen','昆恩','謝','Q123456789','F',34,'新北市中和區莒光路119巷2弄2號','0918123456','queen@gmail.com','image/png',0,10000,0,1,1,0);
Insert into YA803G2.MEMBER (MEMNO,MEMID,MEMPW,FNAME,LNAME,IDNUM,GENDER,LOCNO,ADDR,TEL,EMAIL,MIME,POINT,MONEY,ADDAYS,STATUS,TYPE,WITHHOLD) values (member_seq.NEXTVAL,'rabbit','rabbit','拉貝','吳','R123456789','F',17,'台北市內湖區內湖路二段3號1樓','0982123456','rabbit@gmail.com','image/png',0,10000,0,1,1,0);
Insert into YA803G2.MEMBER (MEMNO,MEMID,MEMPW,FNAME,LNAME,IDNUM,GENDER,LOCNO,ADDR,TEL,EMAIL,MIME,POINT,MONEY,ADDAYS,STATUS,TYPE,WITHHOLD) values (member_seq.NEXTVAL,'super','super','速博','齊','S123456789','M',43,'新北市蘆洲區長安街68巷33號5樓','0988223456','super@gmail.com','image/png',0,10000,0,1,1,0);
Insert into YA803G2.MEMBER (MEMNO,MEMID,MEMPW,FNAME,LNAME,IDNUM,GENDER,LOCNO,ADDR,TEL,EMAIL,MIME,POINT,MONEY,ADDAYS,STATUS,TYPE,WITHHOLD) values (member_seq.NEXTVAL,'tea','tea','提兒','余','T123456789','F',22,'新北市板橋區中山路一段10號3樓','0988122456','tea@gmail.com','image/png',0,10000,0,1,1,0);

--DpsOrd------------------------------------------------------------------
INSERT INTO DPSORD VALUES (dpsord_seq.NEXTVAL,CURRENT_TIMESTAMP,3000,1001,'credit','CANCELLED',null);
INSERT INTO DPSORD VALUES (dpsord_seq.NEXTVAL,CURRENT_TIMESTAMP,700,1002,'ATM','WAITING','223456789012345');
INSERT INTO DPSORD VALUES (dpsord_seq.NEXTVAL,CURRENT_TIMESTAMP,800,1003,'ATM','CANCELLED','123456789012345');
INSERT INTO DPSORD VALUES (dpsord_seq.NEXTVAL,CURRENT_TIMESTAMP,100,1004,'credit','COMPLETED',null);
INSERT INTO DPSORD VALUES (dpsord_seq.NEXTVAL,CURRENT_TIMESTAMP,100,1005,'credit','WAITING',null);
INSERT INTO DPSORD VALUES (dpsord_seq.NEXTVAL,CURRENT_TIMESTAMP,4000,1003,'ATM','COMPLETED','323456789012345');



--WtdReq------------------------------------------------------------------
INSERT INTO WTDREQ VALUES (wtdreq_seq.NEXTVAL,CURRENT_TIMESTAMP,1001,25000,'12345678901234567','COMPLETED');
INSERT INTO WTDREQ VALUES (wtdreq_seq.NEXTVAL,CURRENT_TIMESTAMP,1002,16700,'42345678901234567','COMPLETED');
INSERT INTO WTDREQ VALUES (wtdreq_seq.NEXTVAL,CURRENT_TIMESTAMP,1003,2300,'22345678901234567','WAITING');
INSERT INTO WTDREQ VALUES (wtdreq_seq.NEXTVAL,CURRENT_TIMESTAMP,1004,8000,'32345678901234567','CANCELLED');

--Shop--------------------------------------------------------------------
Insert into YA803G2.SHOP (SHOPNO,MEMNO,TITLE,MIME,LOCNO,ADDR,LAT,LNG,PHONE,FAX,EMAIL,SHIP_DESC,OTHER_DESC,HITS,STATUS) values (SHOP_seq.NEXTVAL,1013,'四平手工饅頭','image/jpeg',9,'重慶北路2段107號1樓',25.057281,121.513918,'02-25531056','02-25531012','tralmg@yahoo.com.tw','滿2200元免運費','1.付款資訊請至「訂購單」中查詢，並依照指定日期完成付款，以便店長準備出貨事宜（付款期限：請於到貨日3天前付款，若到貨日距離下單日為3天內(含3天)，需於下當單日完成付款）。
2.若沒有依規定時間付款，店長有權更改到貨日。
3.如匯入款項錯誤（含多匯、少匯等付款失敗情況），店長會與您連絡款項事宜喔：）',0,2);
Insert into YA803G2.SHOP (SHOPNO,MEMNO,TITLE,MIME,LOCNO,ADDR,LAT,LNG,PHONE,FAX,EMAIL,SHIP_DESC,OTHER_DESC,HITS,STATUS) values (SHOP_seq.NEXTVAL,1013,'vivi日本食品專賣店','image/jpeg',35,'學成路98號',24.9891319,121.450354,'(02)2260-3180',null,'ya803g2@gmail.com','滿2000元免運費
每筆訂單需要滿100元','1.付款資訊請至「訂購單」中查詢，並依照指定日期完成付款，以便店長準備出貨事宜（付款期限：請於到貨日3天前付款，若到貨日距離下單日為3天內(含3天)，需於下當單日完成付款）。
2.若沒有依規定時間付款，店長有權更改到貨日。
3.如匯入款項錯誤（含多匯、少匯等付款失敗情況），店長會與您連絡款項事宜喔：）',0,1);
Insert into YA803G2.SHOP (SHOPNO,MEMNO,TITLE,MIME,LOCNO,ADDR,LAT,LNG,PHONE,FAX,EMAIL,SHIP_DESC,OTHER_DESC,HITS,STATUS) values (SHOP_seq.NEXTVAL,1013,'阿騰伯巨峰葡萄園','image/jpeg',108,'鐮村路605巷25號',24.223612,120.726223,'0425381758','0425380643','dongling.mc@gmail.com','滿8份免運費
每筆訂單份數5份至7份，需付運費270元，離島加收400元
每筆訂單份數1份至2份，需付運費150元，離島加收260元
每筆訂單份數3份至4份，需付運費210元，離島加收340元
每筆訂單需要滿1份','1.付款資訊請至「訂購單」中查詢，並依照指定日期完成付款，以便店長準備出貨事宜（付款期限：請於到貨日3天前付款，若到貨日距離下單日為3天內(含3天)，需於下當單日完成付款）。
2.若沒有依規定時間付款，店長有權更改到貨日。
3.如匯入款項錯誤（含多匯、少匯等付款失敗情況），店長會與您連絡款項事宜喔：）',0,2);
Insert into YA803G2.SHOP (SHOPNO,MEMNO,TITLE,MIME,LOCNO,ADDR,LAT,LNG,PHONE,FAX,EMAIL,SHIP_DESC,OTHER_DESC,HITS,STATUS) values (SHOP_seq.NEXTVAL,1013,'宜蘭餅食品有限公司','image/jpeg',348,'純精路二段130號',24.6769255,121.7637628,'03-9549881','03-9568977','service.icake@msa.hinet.net','每一合購滿3000元，能享有免運費喔！＊外島運費一律 320元喔！
http://www.ihergo.com/store/i-cake/forum/no69066','1.付款資訊請至「訂購單」中查詢，並依照指定日期完成付款，以便店長準備出貨事宜（付款期限：請於到貨日3天前付款，若到貨日距離下單日為3天內(含3天)，需於下當單日完成付款）。
2.若沒有依規定時間付款，店長有權更改到貨日。
3.如匯入款項錯誤（含多匯、少匯等付款失敗情況），店長會與您連絡款項事宜喔：）',0,3);
Insert into YA803G2.SHOP (SHOPNO,MEMNO,TITLE,MIME,LOCNO,ADDR,LAT,LNG,PHONE,FAX,EMAIL,SHIP_DESC,OTHER_DESC,HITS,STATUS) values (SHOP_seq.NEXTVAL,1013,'雅式~手作厚片達人','image/jpeg',205,'青年路319號',22.9915467,120.2141692,'0930554228','062006255','ins_studio@hotmail.com','滿1000元免運費','1.付款資訊請至「訂購單」中查詢，並依照指定日期完成付款，以便店長準備出貨事宜（付款期限：請於到貨日3天前付款，若到貨日距離下單日為3天內(含3天)，需於下當單日完成付款）。 
2.若沒有依規定時間付款，店長有權更改到貨日。 
3.如匯入款項錯誤（含多匯、少匯等付款失敗情況），店長會與您連絡款項事宜喔：）',0,0);
Insert into YA803G2.SHOP (SHOPNO,MEMNO,TITLE,MIME,LOCNO,ADDR,LAT,LNG,PHONE,FAX,EMAIL,SHIP_DESC,OTHER_DESC,HITS,STATUS) values (SHOP_seq.NEXTVAL,1013,'亞尼克果子工房','image/jpeg',17,'瑞湖街178巷15號',25.0708007,121.5759271,'02-87978993#267','02-87978993#267','service.yannick@gmail.com','滿2023元免運費 
每筆訂單需要滿1156元','1.付款資訊請至「訂購單」中查詢，並依照指定日期完成付款，以便店長準備出貨事宜（付款期限：請於到貨日10天前付款，若到貨日距離下單日為10天內(含10天)，需於下當單日完成付款）。 
2.若沒有依規定時間付款，店長有權更改到貨日。 
3.如匯入款項錯誤（含多匯、少匯等付款失敗情況），店長會與您連絡款項事宜喔：）',0,2);
Insert into YA803G2.SHOP (SHOPNO,MEMNO,TITLE,MIME,LOCNO,ADDR,LAT,LNG,PHONE,FAX,EMAIL,SHIP_DESC,OTHER_DESC,HITS,STATUS) values (SHOP_seq.NEXTVAL,1014,'洪記上海生煎包','image/jpeg',16,'石牌路2段56號',25.1160187,121.515934,'0930-999-236',null,'services@boozs.url.tw','滿1000元免運費','1.付款資訊請至「訂購單」中查詢，並依照指定日期完成付款，以便店長準備出貨事宜（付款期限：請於到貨日10天前付款，若到貨日距離下單日為10天內(含10天)，需於下當單日完成付款）。 
2.若沒有依規定時間付款，店長有權更改到貨日。 
3.如匯入款項錯誤（含多匯、少匯等付款失敗情況），店長會與您連絡款項事宜喔：）',0,2);
Insert into YA803G2.SHOP (SHOPNO,MEMNO,TITLE,MIME,LOCNO,ADDR,LAT,LNG,PHONE,FAX,EMAIL,SHIP_DESC,OTHER_DESC,HITS,STATUS) values (SHOP_seq.NEXTVAL,1015,'依蕾特ELATE','image/jpeg',17,'安平路422號',25.0884537,121.5256454,'0800300600','06-2917000','services@elate.url.tw','滿2000元免運費','1.付款資訊請至「訂購單」中查詢，並依照指定日期完成付款，以便店長準備出貨事宜（付款期限：請於到貨日10天前付款，若到貨日距離下單日為10天內(含10天)，需於下當單日完成付款）。 
2.若沒有依規定時間付款，店長有權更改到貨日。 
3.如匯入款項錯誤（含多匯、少匯等付款失敗情況），店長會與您連絡款項事宜喔：）',0,2);
Insert into YA803G2.SHOP (SHOPNO,MEMNO,TITLE,MIME,LOCNO,ADDR,LAT,LNG,PHONE,FAX,EMAIL,SHIP_DESC,OTHER_DESC,HITS,STATUS) values (SHOP_seq.NEXTVAL,1016,'鼎緣福老家滷味館','image/jpeg',100,'中山北路99號',25.0596003,121.5231308,'0987058785',null,'lb556998@gmail.com','滿2000元免運費','1.付款資訊請至「訂購單」中查詢，並依照指定日期完成付款，以便店長準備出貨事宜（付款期限：請於到貨日10天前付款，若到貨日距離下單日為10天內(含10天)，需於下當單日完成付款）。 
2.若沒有依規定時間付款，店長有權更改到貨日。 
3.如匯入款項錯誤（含多匯、少匯等付款失敗情況），店長會與您連絡款項事宜喔：）',0,1);
Insert into YA803G2.SHOP (SHOPNO,MEMNO,TITLE,MIME,LOCNO,ADDR,LAT,LNG,PHONE,FAX,EMAIL,SHIP_DESC,OTHER_DESC,HITS,STATUS) values (SHOP_seq.NEXTVAL,1017,'合鴨米','image/jpeg',10,'信義路59號',25.0596003,121.5231308,'03-9889249','03-9884105','info@hoya-rice.com.tw','滿1000元免運費','1.付款資訊請至「訂購單」中查詢，並依照指定日期完成付款，以便店長準備出貨事宜（付款期限：請於到貨日10天前付款，若到貨日距離下單日為10天內(含10天)，需於下當單日完成付款）。 
2.若沒有依規定時間付款，店長有權更改到貨日。 
3.如匯入款項錯誤（含多匯、少匯等付款失敗情況），店長會與您連絡款項事宜喔：）',0,2);
Insert into YA803G2.SHOP (SHOPNO,MEMNO,TITLE,MIME,LOCNO,ADDR,LAT,LNG,PHONE,FAX,EMAIL,SHIP_DESC,OTHER_DESC,HITS,STATUS) values (SHOP_seq.NEXTVAL,1013,'亞尼克果子工房2店','image/jpeg',17,'瑞湖街178巷15號',25.0708007,121.5759271,'02-87978993#267','02-87978993#267','service.yannick@gmail.com','滿2023元免運費 
每筆訂單需要滿1156元','1.付款資訊請至「訂購單」中查詢，並依照指定日期完成付款，以便店長準備出貨事宜（付款期限：請於到貨日10天前付款，若到貨日距離下單日為10天內(含10天)，需於下當單日完成付款）。 
2.若沒有依規定時間付款，店長有權更改到貨日。 
3.如匯入款項錯誤（含多匯、少匯等付款失敗情況），店長會與您連絡款項事宜喔：）',0,4);
--SHOPPRODUCT---------------------------------------------
Insert into YA803G2.SHOPPRODUCT (SPNO,SHOPNO,NAME,UNITPRICE,PMIME1,PMIME2,PMIME3,PRO_DESC,SUBCATNO,SPEC1,SPEC2,SPEC3,ISRECOMM) values (SHOPPRODUCT_seq.NEXTVAL,2001,'《四平手工饅頭》桂圓核桃(一包5入)',150,'image/jpeg','image/jpeg','image/jpeg','商品說明
一樣的龍眼~老闆排除了大陸低價龍眼，採用台灣台南東山炭火烘烤龍眼，核桃挑選來至美國的核桃，高成本的製作~就是要讓您吃到最健康~最營養的~
注意事項
貨到付款不加手續費~
宅配一律用「大鳥宅配通」冷凍寄出~

當天製作~冷凍可以冰至一個月~食用時，不用解凍，直接冷凍庫取出，電鍋水加一杯左右，蒸10-15分鐘至饅頭軟Q即可~
冷藏可以冰至5-7天~食用時，電鍋水加半杯左右，蒸5-10分鐘至饅頭軟Q即可~
不冷藏、冷凍夏日須隔日食用完畢，純手工~不加防腐劑~',2,'桂圓核桃',null,null,2);
Insert into YA803G2.SHOPPRODUCT (SPNO,SHOPNO,NAME,UNITPRICE,PMIME1,PMIME2,PMIME3,PRO_DESC,SUBCATNO,SPEC1,SPEC2,SPEC3,ISRECOMM) values (SHOPPRODUCT_seq.NEXTVAL,2001,'抹茶紅豆(一包5入)',100,'image/jpeg','image/jpeg','image/jpeg','商品說明
在傳統麵粉中加入水源極佳的南投道地抹茶粉，麵粉散發出淡淡的抹茶香吃起來卻不會澀澀的，搭配裡面月餅專用的紅豆餡(新鮮的小紅豆煮到變成泥狀，咬起來還有紅豆殼的纖維)，抹茶跟紅豆在一起，真是絕配~
注意事項
貨到付款不加手續費~ 
宅配一律用「大鳥宅配通」冷凍寄出~ 

當天製作~冷凍可以冰至一個月~食用時，不用解凍，直接冷凍庫取出，電鍋水加一杯左右，蒸10-15分鐘至饅頭軟Q即可~ 
冷藏可以冰至5-7天~食用時，電鍋水加半杯左右，蒸5-10分鐘至饅頭軟Q即可~ 
不冷藏、冷凍夏日須隔日食用完畢，純手工~不加防腐劑~#XX#',2,'抹茶紅豆',null,null,2);
Insert into YA803G2.SHOPPRODUCT (SPNO,SHOPNO,NAME,UNITPRICE,PMIME1,PMIME2,PMIME3,PRO_DESC,SUBCATNO,SPEC1,SPEC2,SPEC3,ISRECOMM) values (SHOPPRODUCT_seq.NEXTVAL,2001,'鮮奶芋頭(一包5入)',100,'image/jpeg','image/jpeg','image/jpeg','商品說明
在傳統的麵粉中把新鮮的鮮奶當做水下去攪拌，不再加入水，再將鮮奶做的麵皮包覆天然芋頭乳成泥狀的芋頭餡，芋頭餡本身不會太甜,配上鮮奶做的麵皮~實在可口~
注意事項
貨到付款不加手續費~
宅配一律用「大鳥宅配通」冷凍寄出~

當天製作~冷凍可以冰至一個月~食用時，不用解凍，直接冷凍庫取出，電鍋水加一杯左右，蒸10-15分鐘至饅頭軟Q即可~
冷藏可以冰至5-7天~食用時，電鍋水加半杯左右，蒸5-10分鐘至饅頭軟Q即可~
不冷藏、冷凍夏日須隔日食用完畢，純手工~不加防腐劑~',2,'鮮奶芋頭',null,null,2);
Insert into YA803G2.SHOPPRODUCT (SPNO,SHOPNO,NAME,UNITPRICE,PMIME1,PMIME2,PMIME3,PRO_DESC,SUBCATNO,SPEC1,SPEC2,SPEC3,ISRECOMM) values (SHOPPRODUCT_seq.NEXTVAL,2001,'芝麻包(一包5入)',20,'image/jpeg','image/jpeg','image/jpeg','商品說明
在傳統的麵皮中，加入老麵及黑芝麻，Q軟有彈性，加入自製的低糖的芝麻醬(沒有加入油)，香醇可口~
注意事項
貨到付款不加手續費~
宅配一律用「大鳥宅配通」冷凍寄出~

當天製作~冷凍可以冰至一個月~食用時，不用解凍，直接冷凍庫取出，電鍋水加一杯左右，蒸10-15分鐘至饅頭軟Q即可~
冷藏可以冰至5-7天~食用時，電鍋水加半杯左右，蒸5-10分鐘至饅頭軟Q即可~
不冷藏、冷凍夏日須隔日食用完畢，純手工~不加防腐劑~',2,'芝麻包',null,null,2);
Insert into YA803G2.SHOPPRODUCT (SPNO,SHOPNO,NAME,UNITPRICE,PMIME1,PMIME2,PMIME3,PRO_DESC,SUBCATNO,SPEC1,SPEC2,SPEC3,ISRECOMM) values (SHOPPRODUCT_seq.NEXTVAL,2001,'四平手工饅頭_南瓜蔓越苺',20,'image/jpeg','image/jpeg','image/jpeg','商品說明
南瓜可是長壽的養生極品~我們使用新鮮的南瓜削皮打成汁加入高級的麵粉中，再拌入酸酸甜甜的新鮮蔓越苺果子，吃起來有南瓜的清香味又有蔓越莓酸甜得戀愛滋味，在夏天食用式各很爽口的選擇~

因“胖達人”的天然香精事件影響，很多饕者誤以為饅頭會是黃色是色素，非也~我們是使用純天然的南瓜打果汁和麵粉，若您使用南瓜煮濃湯或火鍋，您的湯頭也會呈現金黃色或黃橘色的喔~，因此當您收到饅頭時，麵皮上有很多橘紅色小點點乃是天然的南瓜肉肉，請安心食用~
注意事項
運費190元(大鳥宅配通冷凍寄出)，不論買多少都只收190元喔~若選擇貨到付款，貨到付款手續費30元我們會自行吸收，不加價~
當天製作~冷凍可以冰至一個月~食用時，不用解凍，直接冷凍庫取出，電鍋水加一杯左右，蒸10-15分鐘至饅頭軟Q即可~
冷藏可以冰至5-7天~食用時，電鍋水加半杯左右，蒸5-10分鐘至饅頭軟Q即可~
不冷藏、冷凍夏日須隔日食用完畢，純手工~不加防腐劑~',2,'南瓜蔓越苺',null,null,2);
Insert into YA803G2.SHOPPRODUCT (SPNO,SHOPNO,NAME,UNITPRICE,PMIME1,PMIME2,PMIME3,PRO_DESC,SUBCATNO,SPEC1,SPEC2,SPEC3,ISRECOMM) values (SHOPPRODUCT_seq.NEXTVAL,2001,'抹茶芋頭(一包5入)',100,'image/jpeg','image/jpeg','image/jpeg','商品說明
在傳統麵粉中加入水源極佳的南投道地抹茶粉，麵粉散發出淡淡的抹茶香吃起來卻不會澀澀的，搭配裡面月餅專用的低糖的芋頭餡，別有一番風味~
注意事項
貨到付款不加手續費~ 
宅配一律用「大鳥宅配通」冷凍寄出~ 

當天製作~冷凍可以冰至一個月~食用時，不用解凍，直接冷凍庫取出，電鍋水加一杯左右，蒸10-15分鐘至饅頭軟Q即可~ 
冷藏可以冰至5-7天~食用時，電鍋水加半杯左右，蒸5-10分鐘至饅頭軟Q即可~ 
不冷藏、冷凍夏日須隔日食用完畢，純手工~不加防腐劑~',2,'抹茶芋頭',null,null,2);
Insert into YA803G2.SHOPPRODUCT (SPNO,SHOPNO,NAME,UNITPRICE,PMIME1,PMIME2,PMIME3,PRO_DESC,SUBCATNO,SPEC1,SPEC2,SPEC3,ISRECOMM) values (SHOPPRODUCT_seq.NEXTVAL,2001,'四平手工饅頭_全麥養生堅果饅頭',20,'image/jpeg','image/jpeg','image/jpeg','全麥麵粉製作，加入葡萄乾、枸杞、南瓜籽、核桃、葵花子、杏仁角...等堅果類食材，用料實在~新鮮、營養、可口~多吃堅果，有益心血管，一顆饅頭，補充您對堅果的需求~

注意事項
運費190元(大鳥宅配通冷凍寄出)，不論買多少都只收190元喔~若選擇貨到付款，貨到付款手續費30元我們會自行吸收，不加價~
當天製作~冷凍可以冰至一個月~食用時，不用解凍，直接冷凍庫取出，電鍋水加一杯左右，蒸10-15分鐘至饅頭軟Q即可~
冷藏可以冰至5-7天~食用時，電鍋水加半杯左右，蒸5-10分鐘至饅頭軟Q即可~
不冷藏、冷凍夏日須隔日食用完畢，純手工~不加防腐劑~',2,'全麥養生堅果饅頭',null,null,1);
Insert into YA803G2.SHOPPRODUCT (SPNO,SHOPNO,NAME,UNITPRICE,PMIME1,PMIME2,PMIME3,PRO_DESC,SUBCATNO,SPEC1,SPEC2,SPEC3,ISRECOMM) values (SHOPPRODUCT_seq.NEXTVAL,2001,'全麥爆漿起士饅頭',20,'image/jpeg','image/jpeg','image/jpeg','全麥麵粉製作內包美國煙燻起士(是一片一片的起司片非起司粉喔)，麵皮吃起來賣香Q彈、有勁~，配上軟軟的起士~香味十足~若再搭配一杯香醇的咖啡，簡直是絕配~

注意事項
運費190元(大鳥宅配通冷凍寄出)，不論買多少都只收190元喔~若選擇貨到付款，貨到付款手續費30元我們會自行吸收，不加價~
當天製作~冷凍可以冰至一個月~食用時，不用解凍，直接冷凍庫取出，電鍋水加一杯左右，蒸10-15分鐘至饅頭軟Q即可~
冷藏可以冰至5-7天~食用時，電鍋水加半杯左右，蒸5-10分鐘至饅頭軟Q即可~
不冷藏、冷凍夏日須隔日食用完畢，純手工~不加防腐劑~',2,'全麥爆漿起士饅頭',null,null,1);
Insert into YA803G2.SHOPPRODUCT (SPNO,SHOPNO,NAME,UNITPRICE,PMIME1,PMIME2,PMIME3,PRO_DESC,SUBCATNO,SPEC1,SPEC2,SPEC3,ISRECOMM) values (SHOPPRODUCT_seq.NEXTVAL,2001,'四平手工饅頭_德國起士香腸',25,'image/jpeg','image/jpeg','image/jpeg','在傳統的麵粉中把新鮮的鮮奶當做水下去攪拌，不再加入水，再將鮮奶做的麵皮鋪滿美國進口的煙燻起士，並捲入一條德國熱狗，香香又一點點的鹹味，比大亨堡更好吃，在酷熱的夏日裡吃起來很十分痛快~

注意事項
運費190元(大鳥宅配通冷凍寄出)，不論買多少都只收190元喔~若選擇貨到付款，貨到付款手續費30元我們會自行吸收，不加價~
當天製作~冷凍可以冰至一個月~食用時，不用解凍，直接冷凍庫取出，電鍋水加一杯左右，蒸10-15分鐘至饅頭軟Q即可~
冷藏可以冰至5-7天~食用時，電鍋水加半杯左右，蒸5-10分鐘至饅頭軟Q即可~
不冷藏、冷凍夏日須隔日食用完畢，純手工~不加防腐劑~',2,'德國起士香腸',null,null,1);
Insert into YA803G2.SHOPPRODUCT (SPNO,SHOPNO,NAME,UNITPRICE,PMIME1,PMIME2,PMIME3,PRO_DESC,SUBCATNO,SPEC1,SPEC2,SPEC3,ISRECOMM) values (SHOPPRODUCT_seq.NEXTVAL,2001,'四平手工饅頭-五榖地瓜',30,'image/jpeg','image/jpeg','image/jpeg','商品說明
地瓜高壓清洗完畢後先低溫烘烤再採用整條地瓜包入天然的全麥麵粉和入健康的五穀粒，超有份量的養生五穀地瓜完成了 ~甚至男孩子一次吃一個都感到飽足，全家便利商店的烤地瓜售價一個25元，我們跟他一樣的地瓜並再加麵粉跟五穀粒，
售價不便，一樣25元~',2,'五榖地瓜',null,null,2);
Insert into YA803G2.SHOPPRODUCT (SPNO,SHOPNO,NAME,UNITPRICE,PMIME1,PMIME2,PMIME3,PRO_DESC,SUBCATNO,SPEC1,SPEC2,SPEC3,ISRECOMM) values (SHOPPRODUCT_seq.NEXTVAL,2001,'松露巧克力(一包5入)',100,'image/jpeg','image/jpeg','image/jpeg','商品說明
加入提拉米蘇的巧克力粉，配上好市多的熱銷商品─松露巧克力，夾配做蛋糕專用聖品─核桃，吃起來有巧克力的甜卻不膩，又有核桃的果香味，醫學報導,吃巧克力會使人產生愉快的賀爾蒙~真的是女孩摯愛~情人節聖品~
注意事項
貨到付款不加手續費~
宅配一律用「大鳥宅配通」冷凍寄出~

當天製作~冷凍可以冰至一個月~食用時，不用解凍，直接冷凍庫取出，電鍋水加一杯左右，蒸10-15分鐘至饅頭軟Q即可~
冷藏可以冰至5-7天~食用時，電鍋水加半杯左右，蒸5-10分鐘至饅頭軟Q即可~
不冷藏、冷凍夏日須隔日食用完畢，純手工~不加防腐劑~',2,'松露巧克力',null,null,2);
Insert into YA803G2.SHOPPRODUCT (SPNO,SHOPNO,NAME,UNITPRICE,PMIME1,PMIME2,PMIME3,PRO_DESC,SUBCATNO,SPEC1,SPEC2,SPEC3,ISRECOMM) values (SHOPPRODUCT_seq.NEXTVAL,2001,'四平手工饅頭_鮮奶起士',20,'image/jpeg','image/jpeg','image/jpeg','商品說明
在傳統的麵粉中把新鮮的鮮奶當做水下去攪拌，不再加入水，再將鮮奶做的麵皮鋪滿美國進口的煙薰起士，每咬一口都可以嘗到香濃的起士味及香醇的牛奶香，吃饅頭也可以順便補充對牛奶的需求及起士補鈣的營養~

注意事項
運費190元(大鳥宅配通冷凍寄出)，不論買多少都只收190元喔~若選擇貨到付款，貨到付款手續費30元我們會自行吸收，不加價~
當天製作~冷凍可以冰至一個月~食用時，不用解凍，直接冷凍庫取出，電鍋水加一杯左右，蒸10-15分鐘至饅頭軟Q即可~
冷藏可以冰至5-7天~食用時，電鍋水加半杯左右，蒸5-10分鐘至饅頭軟Q即可~
不冷藏、冷凍夏日須隔日食用完畢，純手工~不加防腐劑~',2,'鮮奶起士',null,null,1);
Insert into YA803G2.SHOPPRODUCT (SPNO,SHOPNO,NAME,UNITPRICE,PMIME1,PMIME2,PMIME3,PRO_DESC,SUBCATNO,SPEC1,SPEC2,SPEC3,ISRECOMM) values (SHOPPRODUCT_seq.NEXTVAL,2002,'日本固力果迪士尼棒棒糖',470,'image/jpeg','image/jpeg','image/jpeg','商品說明
日本原裝進口

重量:9.5g/支

保存期限:民國104年6月(西元2015年6月)

一盒30支,共6種口味:蘇打 可樂 綜合水果 葡萄 柳橙 草莓

可愛氣球包裝,每支包裝上都有可愛迪士尼卡通人物,超可愛的!!',16,'棒棒糖',null,null,1);
Insert into YA803G2.SHOPPRODUCT (SPNO,SHOPNO,NAME,UNITPRICE,PMIME1,PMIME2,PMIME3,PRO_DESC,SUBCATNO,SPEC1,SPEC2,SPEC3,ISRECOMM) values (SHOPPRODUCT_seq.NEXTVAL,2003,'阿騰伯巨峰葡萄',300,'image/jpeg','image/jpeg','image/jpeg','<葡萄營養價值>
* 葡萄是一種營養價值極高的水果，富含多種維生素、蛋白質、氨基酸及礦物質。
* 其中大量的葡萄糖及果糖，較易為人體所吸收，可以在短時間內轉為人體所需的熱量，有助於迅速恢復體力、消除疲勞。
* 另外，含酒石酸及蘋果酸能幫助消化，果膠及單寧酸則可解毒。
* 常吃葡萄可健腦、強心、利尿、開胃、使人強壯、耐風寒，而葡萄的根、莖也可以成為藥引子，可稱為重要水果。
* 葡萄除了當作飯後水果外，還可以釀成葡萄酒、曬成葡萄乾，甚至製成果汁，葡萄乾、葡萄汁富含醣分及豐富的鐵質，具有補血滋養的效果，尤其對生產前後的婦女可保胎氣，而葡萄的果皮所含之礦物質成分則具有調理體內生理機能的功效。
* 現代醫學發現，葡萄皮和葡萄籽中含有一種抗氧化物質白藜蘆醇，對心腦血管病有積極的預防和治療作用。

<葡萄食用說明>
* 清洗葡萄的時候，請用剪刀在蒂頭與果實交接處，小心剪開來，不可剪到葡萄的果肉。
* 千萬不可以用拔的喔，這樣會造成葡萄有傷口，當清洗時水分就會留在傷口處，未食用完的話就容易造成葡萄的腐爛。
* 清洗乾淨後，請用篩子瀝乾，盡量保持乾燥或冷藏並請盡速食用完畢，即可品嚐到葡萄的最佳風味。

<訂購說明>
每滿8盒可享免運費服務(外島需加收差價)',35,'巨峰葡萄',null,null,1);
Insert into YA803G2.SHOPPRODUCT (SPNO,SHOPNO,NAME,UNITPRICE,PMIME1,PMIME2,PMIME3,PRO_DESC,SUBCATNO,SPEC1,SPEC2,SPEC3,ISRECOMM) values (SHOPPRODUCT_seq.NEXTVAL,2004,'特牛奶酪-鏡面巧克力',120,'image/jpeg','image/jpeg','image/jpeg','特牛奶酪以彈性的海綿蛋糕體，包裹著添加日本進口乾酪，鬆軟師潤又帶著濃郁奶香，有別於市場上的奶凍口感，目前已推出咖啡與巧克力口味，可以品嚐新研發的多重滋味。放置於冷藏，口感就像鬆軟綿密的提拉米蘇；放置於冷凍，口感則像香醇濃郁的冰淇淋蛋糕，精巧的特牛奶酪蛋糕，卻能帶來無比的滿足，是值得推薦的美食甜點。
特牛奶酪尺寸：21.5x8x5cm
低溫宅配	本島	外島
6條以下	150元	260元
7-20條	170元	340元
21-40條	220元	400元
40-60條	390元	740元
60條以上	免運費	以一箱40條/400元，論箱計價',1,'鏡面巧克力',null,null,1);
Insert into YA803G2.SHOPPRODUCT (SPNO,SHOPNO,NAME,UNITPRICE,PMIME1,PMIME2,PMIME3,PRO_DESC,SUBCATNO,SPEC1,SPEC2,SPEC3,ISRECOMM) values (SHOPPRODUCT_seq.NEXTVAL,2005,'芝心玉子燒(日式)',50,'image/jpeg','image/jpeg','image/jpeg','建議料理方法
1)開封即食：冰冰吃Q彈香甜
2)蒸烤加熱：香濃起士融化在軟嫩蛋裡，小心燙口!
3)切片料理：可以作蓋飯、握壽司、與親友分享
熱量僅159大卡，一份玉子燒約使用1.3~1.5顆雞蛋，符合一般健康身體每日所需食用量，雞蛋打勻後一定先過篩去掉雜質，再加入雞骨高湯混合，健康無負擔。使用有檢驗合格證明的雞蛋，雞蛋含人體必需的多種氨基酸，與人體蛋白質組成相近，是一種理想的天然“補品”。適合當早午餐，晚餐加菜好選擇。
成份：新鮮雞蛋、高湯原汁
淨重量：150+-10公克
保存方式：冷藏4~7度c，敬請於到貨後1日內食用完畢
注意事項
手作特色
※本產品含有雞蛋，過敏體質患者請斟酌減少食用量。
※新鮮食材下訂才作，無添加糖、味素、人工香料、色素、防腐劑，低膽固醇含量符合每日所需。
※若於開封時發現有湯汁溢出屬冷縮後正常現象，對品質並無影響。',2,'芝心玉子燒(日式)',null,null,1);
Insert into YA803G2.SHOPPRODUCT (SPNO,SHOPNO,NAME,UNITPRICE,PMIME1,PMIME2,PMIME3,PRO_DESC,SUBCATNO,SPEC1,SPEC2,SPEC3,ISRECOMM) values (SHOPPRODUCT_seq.NEXTVAL,2005,'手作韓式泡菜',100,'image/jpeg','image/jpeg','image/jpeg','商品說明
手作特色
※獨家醬汁、天然食材，無添加人工香料、色素、防腐劑，不鹹不甜的爽口滋味。
※傳承媽媽的好手藝，純手工一片片洗滌醃製，保留新鮮白菜的爽脆回甘。
※在地農品下訂才作，使用RO水流動洗淨，保證新鮮、衛生、安全。

主要材料：大白菜
副原料：蒜、薑、小辣椒、韓國辣椒粉、魚露、糖
容量：380+-10公克(含醬汁)
保存方式：冷藏4~7度c
保存期限：3個月，開封後請於1個月內食用完畢，以保最佳風味

注意事項
※為保持食材新鮮，確認訂單後才採購原料進行製作，約7-10天到貨。
※泡菜採天然發酵，沒冰冰箱就會持續發酵，口感越酸為自然現象。
※喜歡清脆口感，請於開封後持續低溫冷藏，請使用公用乾筷夾取泡菜食用。',69,'韓式泡菜',null,null,2);
Insert into YA803G2.SHOPPRODUCT (SPNO,SHOPNO,NAME,UNITPRICE,PMIME1,PMIME2,PMIME3,PRO_DESC,SUBCATNO,SPEC1,SPEC2,SPEC3,ISRECOMM) values (SHOPPRODUCT_seq.NEXTVAL,2005,'芝心玉子燒(重乳酪)',70,'image/jpeg','image/jpeg','image/jpeg','建議料理方法
1)開封即食：冰冰吃Q彈香甜
2)蒸烤加熱：香濃起士融化在軟嫩蛋裡，小心燙口!
3)切片料理：可以作蓋飯、握壽司、與親友分享
熱量僅159大卡，一份玉子燒約使用1.3~1.5顆雞蛋，符合一般健康身體每日所需食用量，雞蛋打勻後一定先過篩去掉雜質，再加入雞骨高湯混合，健康無負擔。使用有檢驗合格證明的雞蛋，雞蛋含人體必需的多種氨基酸，與人體蛋白質組成相近，是一種理想的天然“補品”。適合當早午餐，晚餐加菜好選擇。
成份：新鮮雞蛋、高湯原汁
淨重量：150+-10公克
保存方式：冷藏4~7度c，敬請於到貨後1日內食用完畢

注意事項
手作特色
※本產品含有雞蛋，過敏體質患者請斟酌減少食用量。
※新鮮食材下訂才作，無添加糖、味素、人工香料、色素、防腐劑，低膽固醇含量符合每日所需。
※若於開封時發現有湯汁溢出屬冷縮後正常現象，對品質並無影響。',2,'芝心玉子燒',null,null,2);
Insert into YA803G2.SHOPPRODUCT (SPNO,SHOPNO,NAME,UNITPRICE,PMIME1,PMIME2,PMIME3,PRO_DESC,SUBCATNO,SPEC1,SPEC2,SPEC3,ISRECOMM) values (SHOPPRODUCT_seq.NEXTVAL,2007,'紅豆麻吉包(素)',66,'image/jpeg','image/jpeg','image/jpeg','本店特別開發出甜食口味 
搭配特有的Q彈麵皮 
吃的到紅豆碎顆粒 
以及大份量的手工麻糬 
在炎炎夏日裡 來顆紅豆麻吉包 
不外乎是另一種享受 
每天各店採限量推出方式 
單顆重量約85g+-5g',26,'6入',null,null,2);
Insert into YA803G2.SHOPPRODUCT (SPNO,SHOPNO,NAME,UNITPRICE,PMIME1,PMIME2,PMIME3,PRO_DESC,SUBCATNO,SPEC1,SPEC2,SPEC3,ISRECOMM) values (SHOPPRODUCT_seq.NEXTVAL,2007,'韭菜包',66,'image/jpeg','image/jpeg','image/jpeg','富有特殊香氣的嚴選韭菜 
在口味特調上 
特別用心加入了 
蝦米及豆干 還有滑嫩的冬粉 
豐富了口感上多層次感覺 
單顆重量約85g+-5g',26,'6入',null,null,1);
Insert into YA803G2.SHOPPRODUCT (SPNO,SHOPNO,NAME,UNITPRICE,PMIME1,PMIME2,PMIME3,PRO_DESC,SUBCATNO,SPEC1,SPEC2,SPEC3,ISRECOMM) values (SHOPPRODUCT_seq.NEXTVAL,2007,'高麗菜包(素)',66,'image/jpeg','image/jpeg','image/jpeg','堅持以純手工方式 
用心切出完美比例之高麗菜 
讓您不會吃到硬硬的菜梗 
搭配特調的素食醬汁 
與少許的香菇 
點綴出高麗菜的青脆口感 
讓廣大的素食朋友 
更多了一種特別的選擇 
單顆重量約90g+-5g',26,'6入',null,null,2);
Insert into YA803G2.SHOPPRODUCT (SPNO,SHOPNO,NAME,UNITPRICE,PMIME1,PMIME2,PMIME3,PRO_DESC,SUBCATNO,SPEC1,SPEC2,SPEC3,ISRECOMM) values (SHOPPRODUCT_seq.NEXTVAL,2007,'鮮肉包',66,'image/jpeg','image/jpeg','image/jpeg','使用當日新鮮溫體豬肉調製 
以瘦肉80%+肥肉20%黃金比率醃漬 
搭配少許青蔥作提味 美味升級 
讓您口口滿足 
完全不會有任何油膩感 
單顆重量約85g+-5g',26,'6入',null,null,2);
Insert into YA803G2.SHOPPRODUCT (SPNO,SHOPNO,NAME,UNITPRICE,PMIME1,PMIME2,PMIME3,PRO_DESC,SUBCATNO,SPEC1,SPEC2,SPEC3,ISRECOMM) values (SHOPPRODUCT_seq.NEXTVAL,2007,'水煎包任選口味,6入一袋,36顆裝',432,'image/jpeg','image/jpeg','image/jpeg','使用當日新鮮溫體豬肉調製 
以瘦肉80%+肥肉20%黃金比率醃漬 
搭配少許青蔥作提味 美味升級 
讓您口口滿足 
完全不會有任何油膩感 
單顆重量約85g+-5g',26,'高麗菜','韭菜','鮮肉',1);
Insert into YA803G2.SHOPPRODUCT (SPNO,SHOPNO,NAME,UNITPRICE,PMIME1,PMIME2,PMIME3,PRO_DESC,SUBCATNO,SPEC1,SPEC2,SPEC3,ISRECOMM) values (SHOPPRODUCT_seq.NEXTVAL,2008,'鮮奶布丁',360,'image/jpeg','image/jpeg','image/jpeg','乳香濃郁的鮮奶 參和鮮美的蛋汁 
調理製成如同白漿凝玉液 透著嬌黃的細嫩布丁 
香濃襲人 讓人饞涎欲滴 
■冷藏賞味期14天，室溫下請勿超過3-4小時 
■主原料：鮮奶、蛋、鮮奶油 
■副原料：砂糖、香草水、糖漿 
■內容量：170±5g 
■熱量：212大卡',7,'12個/盒',null,null,1);
Insert into YA803G2.SHOPPRODUCT (SPNO,SHOPNO,NAME,UNITPRICE,PMIME1,PMIME2,PMIME3,PRO_DESC,SUBCATNO,SPEC1,SPEC2,SPEC3,ISRECOMM) values (SHOPPRODUCT_seq.NEXTVAL,2008,'可可奶酪',360,'image/jpeg','image/jpeg','image/jpeg','可可與牛奶的完美搭配 
調和濃郁的咖啡醬汁 
典雅誘人的色澤與風味 
令人垂涎 
■冷藏賞味期14天，室溫下請勿超過3-4時 
■主原料：鮮奶、鮮奶油、奶粉、可可粉 
■副原料：砂糖、咖啡粉、乳化劑、海藻抽出物 
■內容量：170±5g 
■熱量：219大卡',7,'12個/盒',null,null,2);
Insert into YA803G2.SHOPPRODUCT (SPNO,SHOPNO,NAME,UNITPRICE,PMIME1,PMIME2,PMIME3,PRO_DESC,SUBCATNO,SPEC1,SPEC2,SPEC3,ISRECOMM) values (SHOPPRODUCT_seq.NEXTVAL,2008,'芒果奶酪',360,'image/jpeg','image/jpeg','image/jpeg','嬌黃滑嫩的奶酪 
淋上甘甜艷黃的香濃芒果泥 
共譜出完美的協奏曲 
風味細緻    令人激賞 
■冷藏賞味期14天，室溫下請勿超過3-4小時 
■主原料：鮮奶、鮮奶油、芒果泥、奶粉 
■副原料：砂糖、乳化劑、海藻抽出物 
■內容量：170±5g 
■熱量：172大卡',7,'12個/盒',null,null,2);
Insert into YA803G2.SHOPPRODUCT (SPNO,SHOPNO,NAME,UNITPRICE,PMIME1,PMIME2,PMIME3,PRO_DESC,SUBCATNO,SPEC1,SPEC2,SPEC3,ISRECOMM) values (SHOPPRODUCT_seq.NEXTVAL,2009,'招牌滷味綜合包',69,'image/jpeg','image/jpeg','image/jpeg','重量: 380g ± 10%  
內容物: 滷米血、黑輪片、百頁豆腐、招牌海帶、小豆干',23,'1份',null,null,2);
Insert into YA803G2.SHOPPRODUCT (SPNO,SHOPNO,NAME,UNITPRICE,PMIME1,PMIME2,PMIME3,PRO_DESC,SUBCATNO,SPEC1,SPEC2,SPEC3,ISRECOMM) values (SHOPPRODUCT_seq.NEXTVAL,2009,'超夯滷味綜合包',149,'image/jpeg','image/jpeg','image/jpeg','重量: 500g±10% 
內容物: 滷米血、杏包菇、滷皮蛋、大豆干、百頁、嘴邊肉',23,'1份',null,null,1);
Insert into YA803G2.SHOPPRODUCT (SPNO,SHOPNO,NAME,UNITPRICE,PMIME1,PMIME2,PMIME3,PRO_DESC,SUBCATNO,SPEC1,SPEC2,SPEC3,ISRECOMM) values (SHOPPRODUCT_seq.NEXTVAL,2010,'合鴨米(白米)',225,'image/jpeg','image/jpeg','image/jpeg','『合鴨米(白米)』- 耕作全程不使用農藥、化學肥料、除草劑的奇蹟。

利用合鴨好動的本性，終日悠遊於稻株之間，直接啄食害蟲或藉鴨翅拍動，使害蟲掉落水面而啄食，由於合鴨有不吃禾本科的特性，所以不至於傷害秧株，但是雜草卻無所遁形，且稻株受合鴨刺激，有如中耕效果，使秧苗更加茁壯。合鴨每天活動量大，水田中溶氧增加，使米飯香Q好吃。

成份：合鴨白米

品種：台中秈10號

產地：宜蘭縣

內容量：1.5公斤±100公克

保存期限：6個月',41,'每包1.5公斤',null,null,1);
Insert into YA803G2.SHOPPRODUCT (SPNO,SHOPNO,NAME,UNITPRICE,PMIME1,PMIME2,PMIME3,PRO_DESC,SUBCATNO,SPEC1,SPEC2,SPEC3,ISRECOMM) values (SHOPPRODUCT_seq.NEXTVAL,2006,'十勝生巧克力',380,'image/jpeg','image/jpeg','image/jpeg','◆商品名稱：十勝生巧克力  
◆商品規格：20入 單顆3 x 2 x 0.8公分 淨重：120±5g       
◆商品成分：法國米歇爾黑巧克力/日本生鮮奶油/法國無鹽發酵奶油/天然香草棒/D-山梨醇/轉化糖漿 
◆保存期限：5度C冷藏7天 (需扣除宅配1天)(本商品為新鮮食材製作，不含防腐劑) 
◆食用建議:因家用冰箱非專業級 冷藏溫度略微不精準 建議進早食用完畢 避免喪失最佳風味! 
◆葷素：蛋奶素 
◆配送方式：冷藏宅配 (黑貓宅急便為您全程低溫配送)',9,'20入','30入','40入',1);

--ShopRep-----------------------------------------------------------------
INSERT INTO SHOPREP VALUES (shoprep_seq.NEXTVAL,2001,1003,'跟圖片長得都不一樣！覺得被騙QQ');
INSERT INTO SHOPREP VALUES (shoprep_seq.NEXTVAL,2001,1003,'餡料超少！覺得被騙QQ');
INSERT INTO SHOPREP VALUES (shoprep_seq.NEXTVAL,2002,1003,'覺得被騙QQ');

--CaseProduct-------------------------------------------------------------
/* cpno, memno, name, unitprice, pic1, pic2, pic3, pmime1, pmime2, pmime3, cpdesc, subcatno */

/*User #1*/
Insert into CASEPRODUCT (CPNO,MEMNO,NAME,UNITPRICE,SUBCATNO,LOCKFLAG) values (caseProduct_seq.nextval,1001,'甘蔗雞', 500,57,0);
Insert into CASEPRODUCT (CPNO,MEMNO,NAME,UNITPRICE,SUBCATNO,LOCKFLAG) values (caseProduct_seq.nextval,1001,'二結羊肉爐',400,58,0);
Insert into CASEPRODUCT (CPNO,MEMNO,NAME,UNITPRICE,SUBCATNO,LOCKFLAG) values (caseProduct_seq.nextval,1001,'衝喜鴨血 高評價回購率高的麻辣鍋底',200,58,0);
Insert into CASEPRODUCT (CPNO,MEMNO,NAME,UNITPRICE,SUBCATNO,LOCKFLAG) values (caseProduct_seq.nextval,1001,'麻油杏鮑菇',150,58,0);

/*User #2*/
Insert into CASEPRODUCT (CPNO,MEMNO,NAME,UNITPRICE,SUBCATNO,LOCKFLAG) values (caseProduct_seq.nextval,1002,'白木耳露',150,50,0);
Insert into CASEPRODUCT (CPNO,MEMNO,NAME,UNITPRICE,SUBCATNO,LOCKFLAG) values (caseProduct_seq.nextval,1002,'乳酪起士條',199,19,0);
Insert into CASEPRODUCT (CPNO,MEMNO,NAME,UNITPRICE,SUBCATNO,LOCKFLAG) values (caseProduct_seq.nextval,1002,'有機紅茶菌氣泡飲料-瓶裝 414ML',1200,52,0);
 
/*User #3*/
Insert into CASEPRODUCT (CPNO,MEMNO,NAME,UNITPRICE,SUBCATNO,LOCKFLAG) values (caseProduct_seq.nextval,1003,'五行水餃',200,38,1);
Insert into CASEPRODUCT (CPNO,MEMNO,NAME,UNITPRICE,SUBCATNO,LOCKFLAG) values (caseProduct_seq.nextval,1003,'蛋黃包 肉包',220,23,1);
Insert into CASEPRODUCT (CPNO,MEMNO,NAME,UNITPRICE,SUBCATNO,LOCKFLAG) values (caseProduct_seq.nextval,1003,'鹹酥蔥餅(6入/份)',80,30,0);

/*User #4*/
Insert into CASEPRODUCT (CPNO,MEMNO,NAME,UNITPRICE,SUBCATNO,LOCKFLAG) values (caseProduct_seq.nextval,1004,'黃金泡菜',250,25,0);
Insert into CASEPRODUCT (CPNO,MEMNO,NAME,UNITPRICE,SUBCATNO,LOCKFLAG) values (caseProduct_seq.nextval,1004,'益康泡菜',200,25,0);

/*User #5*/
Insert into CASEPRODUCT (CPNO,MEMNO,NAME,UNITPRICE,SUBCATNO,LOCKFLAG) values (caseProduct_seq.nextval,1005,'五層酥脆口感,黑巧克力口味',40,15,0);
Insert into CASEPRODUCT (CPNO,MEMNO,NAME,UNITPRICE,SUBCATNO,LOCKFLAG) values (caseProduct_seq.nextval,1005,'冷凍茶豆莢',300,32,0);
Insert into CASEPRODUCT (CPNO,MEMNO,NAME,UNITPRICE,SUBCATNO,LOCKFLAG) values (caseProduct_seq.nextval,1005,'大成勁嫩雞腿排',100,74,0);

/*User #6*/
Insert into CASEPRODUCT (CPNO,MEMNO,NAME,UNITPRICE,SUBCATNO,LOCKFLAG) values (caseProduct_seq.nextval,1006,'法式櫻桃鴨胸',200,74,0);
Insert into CASEPRODUCT (CPNO,MEMNO,NAME,UNITPRICE,SUBCATNO,LOCKFLAG) values (caseProduct_seq.nextval,1006,'手工冰淇淋+蘇打餅乾',30,55,0);
Insert into CASEPRODUCT (CPNO,MEMNO,NAME,UNITPRICE,SUBCATNO,LOCKFLAG) values (caseProduct_seq.nextval,1006,'手工冰淇淋+雞蛋糕餅皮',35,55,0);
Insert into CASEPRODUCT (CPNO,MEMNO,NAME,UNITPRICE,SUBCATNO,LOCKFLAG) values (caseProduct_seq.nextval,1006,'豬腳',200,74,0);
--Cases-------------------------------------------------------------------
/* caseno, title, memno, cpno, spno, locno, discount, 
stime, 
etime, 
minqty, maxqty, status, hits, casedesc, ship1, shipcost1, ship2, shipcost2, threshold*/
Insert into YA803G2.CASES (CASENO,TITLE,MEMNO,CPNO,SPNO,LOCNO,DISCOUNT,STIME,ETIME,MINQTY,MAXQTY,STATUS,HITS,CASEDESC,SHIP1,SHIPCOST1,SHIP2,SHIPCOST2,THRESHOLD) values (cases_seq.NEXTVAL,'【慕鈺華】五行水餃',1003,4008,null,22,20,to_timestamp('10-9月 -14 03.15.10.000000000 下午','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('20-9月 -14 03.15.10.000000000 下午','DD-MON-RR HH.MI.SSXFF AM'),10,100,4,257,'包含：原味韭菜+菠菜蔥肉+甜菜根高麗菜+紅蘿蔔泡菜+南瓜玉米各七顆。','面交',0,'郵寄',60,0);
Insert into YA803G2.CASES (CASENO,TITLE,MEMNO,CPNO,SPNO,LOCNO,DISCOUNT,STIME,ETIME,MINQTY,MAXQTY,STATUS,HITS,CASEDESC,SHIP1,SHIPCOST1,SHIP2,SHIPCOST2,THRESHOLD) values (cases_seq.NEXTVAL,'金露園黑與白的邂逅 新品白木耳露',1002,4005,null,23,50,to_timestamp('15-10月-14 03.15.10.000000000 下午','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('15-11月-14 03.15.10.000000000 下午','DD-MON-RR HH.MI.SSXFF AM'),20,60,6,0,'快來買喔~','面交',0,'郵寄',60,0);
Insert into YA803G2.CASES (CASENO,TITLE,MEMNO,CPNO,SPNO,LOCNO,DISCOUNT,STIME,ETIME,MINQTY,MAXQTY,STATUS,HITS,CASEDESC,SHIP1,SHIPCOST1,SHIP2,SHIPCOST2,THRESHOLD) values (cases_seq.NEXTVAL,'招牌甘蔗雞 全隻免運 一隻也可宅配',1001,4001,null,24,80,to_timestamp('07-10月-14 06.18.40.000000000 下午','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('30-10月-14 06.18.40.000000000 下午','DD-MON-RR HH.MI.SSXFF AM'),5,20,6,0,'雞隻重量：整隻約 2斤12～3斤 (切塊裝盒會失重) 
保存期限：冷藏3天．冷凍30天 (下標才製作不含防腐劑請儘早食用)  
食用方式：  
1．未食用完之雞肉請冷藏  
2．於冰箱拿出來食用，切記！勿微波加熱或蒸煮，以免影響原有風味  
3．食用前提前30分鐘由冰箱拿出來放置回溫即可食用 
4．如不切請留言或通知 沒通知不切一律切塊包裝 
訂購團購電話:0958992999 阿弟仔','面交',0,'郵寄',60,0);
Insert into YA803G2.CASES (CASENO,TITLE,MEMNO,CPNO,SPNO,LOCNO,DISCOUNT,STIME,ETIME,MINQTY,MAXQTY,STATUS,HITS,CASEDESC,SHIP1,SHIPCOST1,SHIP2,SHIPCOST2,THRESHOLD) values (cases_seq.NEXTVAL,'手工蛋黃肉包 香菇肉包',1003,4009,null,50,30,to_timestamp('01-8月 -14 08.27.00.000000000 下午','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('16-8月 -14 08.00.00.000000000 下午','DD-MON-RR HH.MI.SSXFF AM'),10,30,4,294,'歡迎參加!','面交',0,null,0,0);
Insert into YA803G2.CASES (CASENO,TITLE,MEMNO,CPNO,SPNO,LOCNO,DISCOUNT,STIME,ETIME,MINQTY,MAXQTY,STATUS,HITS,CASEDESC,SHIP1,SHIPCOST1,SHIP2,SHIPCOST2,THRESHOLD) values (cases_seq.NEXTVAL,'二結羊肉爐 補冬節優惠小朋友的最愛',1001,4002,null,22,25,to_timestamp('30-11月-14 03.01.06.389000000 下午','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('30-11月-14 04.05.12.466000000 下午','DD-MON-RR HH.MI.SSXFF AM'),3,10,3,24,'取貨當天如有事情無法取貨麻煩請務必來電告知主購，並約定時間自取；請人代領者須事先告知主購。
不代冰！
請到貨當天取貨。當天無法來面交者，請一天前寫信告知，並加收代冰費 10元／天，作為補貼電費之用。','面交',0,null,0,0);
Insert into YA803G2.CASES (CASENO,TITLE,MEMNO,CPNO,SPNO,LOCNO,DISCOUNT,STIME,ETIME,MINQTY,MAXQTY,STATUS,HITS,CASEDESC,SHIP1,SHIPCOST1,SHIP2,SHIPCOST2,THRESHOLD) values (cases_seq.NEXTVAL,'衝喜鴨血 高評價回購率高的麻辣鍋底',1001,4003,null,33,48,to_timestamp('30-11月-14 05.35.00.828000000 下午','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('30-11月-14 06.43.46.815000000 下午','DD-MON-RR HH.MI.SSXFF AM'),10,50,3,21,'取貨當天未來取貨者~~貨品一律分給小英雄家左鄰右舍 不要隔天再來告訴我忘了要取貨~~要改約其他時間
(最近太多問題了~~特地加上此點~)

注意事項:
o  響應環保請自備購物袋
o  超過時間不主動聯絡者，商品由主購處理囉! ','面交含雜費',5,null,0,0);
Insert into YA803G2.CASES (CASENO,TITLE,MEMNO,CPNO,SPNO,LOCNO,DISCOUNT,STIME,ETIME,MINQTY,MAXQTY,STATUS,HITS,CASEDESC,SHIP1,SHIPCOST1,SHIP2,SHIPCOST2,THRESHOLD) values (cases_seq.NEXTVAL,'金露園黑與白的邂逅 新品白木耳露',1002,4005,null,49,20,to_timestamp('30-11月-14 07.33.55.126000000 下午','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('02-12月-14 11.00.00.000000000 下午','DD-MON-RR HH.MI.SSXFF AM'),20,60,1,0,'好喝喔

快來買吧!

面交地點為中央大學後門(中央路底)','面交',0,null,null,0);


--CaseRep-----------------------------------------------------------------
INSERT INTO CASEREP VALUES (caserep_seq.NEXTVAL,1006,1003,5001,'到處騙錢還好意思出來');
INSERT INTO CASEREP VALUES (caserep_seq.NEXTVAL,1007,1003,5001,'播下希望的種子，鬼才信');
INSERT INTO CASEREP VALUES (caserep_seq.NEXTVAL,1008,1001,5003,'怎麼還沒回家吃自己');

--CaseQA------------------------------------------------------------------
/*qano, memno, caseno, question, answer, qtime, atime*/

Insert into YA803G2.CASEQA (QANO,MEMNO,CASENO,QUESTION,ANSWER,QTIME,ATIME) values (caseqa_seq.NEXTVAL,1002,5001,'安安','安安',to_timestamp('11-9月 -14 03.15.10.000000000 下午','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('11-9月 -14 08.15.10.000000000 下午','DD-MON-RR HH.MI.SSXFF AM'));
Insert into YA803G2.CASEQA (QANO,MEMNO,CASENO,QUESTION,ANSWER,QTIME,ATIME) values (caseqa_seq.NEXTVAL,1008,5001,'維大力？','義大利',to_timestamp('12-9月 -14 03.15.10.000000000 下午','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('12-9月 -14 08.15.10.000000000 下午','DD-MON-RR HH.MI.SSXFF AM'));
Insert into YA803G2.CASEQA (QANO,MEMNO,CASENO,QUESTION,ANSWER,QTIME,ATIME) values (caseqa_seq.NEXTVAL,1004,5001,'你好請問是用餿水油嗎','是皮革油喔',to_timestamp('13-9月 -14 03.15.10.000000000 下午','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('13-9月 -14 08.15.10.000000000 下午','DD-MON-RR HH.MI.SSXFF AM'));
Insert into YA803G2.CASEQA (QANO,MEMNO,CASENO,QUESTION,ANSWER,QTIME,ATIME) values (caseqa_seq.NEXTVAL,1005,5001,'你好請問有添加塑化劑嗎','你好，標準添加200ppm喔',to_timestamp('14-9月 -14 03.15.10.000000000 下午','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('14-9月 -14 08.15.10.000000000 下午','DD-MON-RR HH.MI.SSXFF AM'));
Insert into YA803G2.CASEQA (QANO,MEMNO,CASENO,QUESTION,ANSWER,QTIME,ATIME) values (caseqa_seq.NEXTVAL,1006,5001,'是鎘米嗎？','不是喔，是鉛米',to_timestamp('15-9月 -14 03.15.10.000000000 下午','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('15-9月 -14 08.15.10.000000000 下午','DD-MON-RR HH.MI.SSXFF AM'));
Insert into YA803G2.CASEQA (QANO,MEMNO,CASENO,QUESTION,ANSWER,QTIME,ATIME) values (caseqa_seq.NEXTVAL,1007,5001,'ㄏㄏ','你有事嗎？',to_timestamp('16-9月 -14 03.15.10.000000000 下午','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('16-9月 -14 08.15.10.000000000 下午','DD-MON-RR HH.MI.SSXFF AM'));
Insert into YA803G2.CASEQA (QANO,MEMNO,CASENO,QUESTION,ANSWER,QTIME,ATIME) values (caseqa_seq.NEXTVAL,1007,5001,'請問是否可以不混搭(同一種口味)???','您好，還有蛋黃肉包10顆裝的和香菇肉包10顆裝兩種選擇喔',to_timestamp('16-9月 -14 03.15.10.000000000 下午','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('16-9月 -14 08.15.10.000000000 下午','DD-MON-RR HH.MI.SSXFF AM'));
Insert into YA803G2.CASEQA (QANO,MEMNO,CASENO,QUESTION,ANSWER,QTIME,ATIME) values (caseqa_seq.NEXTVAL,1005,5006,'這個會不會很辣啊','還好喔
如果怕辣的話可以加適量的水稀釋',to_timestamp('30-11月-14 06.08.15.202000000 下午','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('30-11月-14 06.08.52.387000000 下午','DD-MON-RR HH.MI.SSXFF AM'));
Insert into YA803G2.CASEQA (QANO,MEMNO,CASENO,QUESTION,ANSWER,QTIME,ATIME) values (caseqa_seq.NEXTVAL,1003,5006,'請問可以幫忙保管兩天嗎？剛好出差不在','不好意思沒有辦法欸
還是您要找朋友或家人代領呢？',to_timestamp('30-11月-14 06.09.39.780000000 下午','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('30-11月-14 06.10.11.091000000 下午','DD-MON-RR HH.MI.SSXFF AM'));
Insert into YA803G2.CASEQA (QANO,MEMNO,CASENO,QUESTION,ANSWER,QTIME,ATIME) values (caseqa_seq.NEXTVAL,1003,5006,'好，那我找認識的人去幫我拿','OK，謝謝囉',to_timestamp('30-11月-14 06.10.35.223000000 下午','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('30-11月-14 06.10.51.632000000 下午','DD-MON-RR HH.MI.SSXFF AM'));


--Orders------------------------------------------------------------------
/*ordno, bmemno, cmemno, caseno, qty, price, ordtime, status, brate, bratedesc, crate, cratedesc*/
Insert into YA803G2.ORDERS (ORDNO,BMEMNO,CMEMNO,CASENO,QTY,PRICE,ORDTIME,STATUS,BRATE,BRATEDESC,CRATE,CRATEDESC,SHIP) values (orders_seq.NEXTVAL,1004,1003,5001,10,1800,to_timestamp('14-9月 -14 08.15.10.000000000 下午','DD-MON-RR HH.MI.SSXFF AM'),5,2,'銘謝惠顧!',2,'感謝! 很好吃',1);
Insert into YA803G2.ORDERS (ORDNO,BMEMNO,CMEMNO,CASENO,QTY,PRICE,ORDTIME,STATUS,BRATE,BRATEDESC,CRATE,CRATEDESC,SHIP) values (orders_seq.NEXTVAL,1005,1003,5001,15,2700,to_timestamp('15-9月 -14 08.15.10.000000000 下午','DD-MON-RR HH.MI.SSXFF AM'),5,2,'銘謝惠顧!',2,'謝謝啦',1);
Insert into YA803G2.ORDERS (ORDNO,BMEMNO,CMEMNO,CASENO,QTY,PRICE,ORDTIME,STATUS,BRATE,BRATEDESC,CRATE,CRATEDESC,SHIP) values (orders_seq.NEXTVAL,1006,1003,5001,10,1800,to_timestamp('16-9月 -14 08.15.10.000000000 下午','DD-MON-RR HH.MI.SSXFF AM'),5,2,'銘謝惠顧!',2,'不錯吃唷',1);
Insert into YA803G2.ORDERS (ORDNO,BMEMNO,CMEMNO,CASENO,QTY,PRICE,ORDTIME,STATUS,BRATE,BRATEDESC,CRATE,CRATEDESC,SHIP) values (orders_seq.NEXTVAL,1007,1003,5001,5,900,to_timestamp('17-9月 -14 08.15.10.000000000 下午','DD-MON-RR HH.MI.SSXFF AM'),5,2,'銘謝惠顧!',2,'啦啦',1);
Insert into YA803G2.ORDERS (ORDNO,BMEMNO,CMEMNO,CASENO,QTY,PRICE,ORDTIME,STATUS,BRATE,BRATEDESC,CRATE,CRATEDESC,SHIP) values (orders_seq.NEXTVAL,1002,1001,5005,2,750,to_timestamp('30-11月-14 03.57.38.054000000 下午','DD-MON-RR HH.MI.SSXFF AM'),5,2,'感謝喔',2,'感謝!',1);
Insert into YA803G2.ORDERS (ORDNO,BMEMNO,CMEMNO,CASENO,QTY,PRICE,ORDTIME,STATUS,BRATE,BRATEDESC,CRATE,CRATEDESC,SHIP) values (orders_seq.NEXTVAL,1003,1001,5005,3,1125,to_timestamp('30-11月-14 03.58.58.464000000 下午','DD-MON-RR HH.MI.SSXFF AM'),5,2,'謝謝!',2,'讚',1);
Insert into YA803G2.ORDERS (ORDNO,BMEMNO,CMEMNO,CASENO,QTY,PRICE,ORDTIME,STATUS,BRATE,BRATEDESC,CRATE,CRATEDESC,SHIP) values (orders_seq.NEXTVAL,1004,1001,5005,3,1125,to_timestamp('30-11月-14 03.59.16.263000000 下午','DD-MON-RR HH.MI.SSXFF AM'),5,2,'謝啦',2,'謝謝喔',1);
Insert into YA803G2.ORDERS (ORDNO,BMEMNO,CMEMNO,CASENO,QTY,PRICE,ORDTIME,STATUS,BRATE,BRATEDESC,CRATE,CRATEDESC,SHIP) values (orders_seq.NEXTVAL,1001,1001,5006,1,157,to_timestamp('30-11月-14 06.06.08.072000000 下午','DD-MON-RR HH.MI.SSXFF AM'),1,null,null,null,null,1);
Insert into YA803G2.ORDERS (ORDNO,BMEMNO,CMEMNO,CASENO,QTY,PRICE,ORDTIME,STATUS,BRATE,BRATEDESC,CRATE,CRATEDESC,SHIP) values (orders_seq.NEXTVAL,1002,1001,5006,5,765,to_timestamp('30-11月-14 06.06.50.266000000 下午','DD-MON-RR HH.MI.SSXFF AM'),1,null,null,2,'超迅速!',1);
Insert into YA803G2.ORDERS (ORDNO,BMEMNO,CMEMNO,CASENO,QTY,PRICE,ORDTIME,STATUS,BRATE,BRATEDESC,CRATE,CRATEDESC,SHIP) values (orders_seq.NEXTVAL,1003,1001,5006,3,461,to_timestamp('30-11月-14 06.07.07.270000000 下午','DD-MON-RR HH.MI.SSXFF AM'),1,null,null,null,null,1);
Insert into YA803G2.ORDERS (ORDNO,BMEMNO,CMEMNO,CASENO,QTY,PRICE,ORDTIME,STATUS,BRATE,BRATEDESC,CRATE,CRATEDESC,SHIP) values (orders_seq.NEXTVAL,1004,1001,5006,1,157,to_timestamp('30-11月-14 06.07.16.926000000 下午','DD-MON-RR HH.MI.SSXFF AM'),1,null,null,null,null,1);
Insert into YA803G2.ORDERS (ORDNO,BMEMNO,CMEMNO,CASENO,QTY,PRICE,ORDTIME,STATUS,BRATE,BRATEDESC,CRATE,CRATEDESC,SHIP) values (orders_seq.NEXTVAL,1005,1001,5006,3,461,to_timestamp('30-11月-14 06.07.56.187000000 下午','DD-MON-RR HH.MI.SSXFF AM'),1,null,null,null,null,1);


--WishLisst---------------------------------------------------------------
INSERT INTO WISHLIST VALUES (wishlist_seq.NEXTVAL,1001,5001);
INSERT INTO WISHLIST VALUES (wishlist_seq.NEXTVAL,1001,5002);

--NEWS--------------------------------------------------------------------
INSERT INTO NEWS(NEWSNO,TITLE,TEXT) VALUES (NEWS_seq.NEXTVAL,'冬季感恩回饋','各位主購們：
又到了十月感恩回饋的時刻，今年我們特地新增了12包快速成團，運費只需100元!
薑母鍋 原價100元 特價90元
九尾鍋 原價100元 特價90元
紅燒鍋 原價120元 特價110元
');

INSERT INTO NEWS(NEWSNO,TITLE,TEXT) VALUES (NEWS_seq.NEXTVAL,'試吃推廣活動~真實料多、味美、麵Q彈~高評價義大利麵',
'敝店是以沙拉油、安佳奶油及自煉鴨油做為調理食用油，敬請安心食用~
新增提供銅板價義大利麵醬料包~真的有料~系列
敝店醬汁的濃郁與麵條的Q彈都有再做過調整~歡迎嚐鮮惠顧~
即日起試吃推廣活動~真實料多、味美、麵Q彈~高評價義大利麵
~6份以上義大利麵整組(醬含麵)一律免運費
~12份以上醬料包(不含麵)一律免運費
以上推廣活動(店家保留活動終止日權)
下單後店家會刪除運費~並麻煩先與店家確定到貨日~感謝^^
');

INSERT INTO NEWS(NEWSNO,TITLE,TEXT) VALUES (NEWS_seq.NEXTVAL,'萬聖節狂歡派對開跑!不降價就搗蛋!買到賺到!','萬聖節狂歡派對全店3%回饋金喔~');

INSERT INTO NEWS(NEWSNO,TITLE,TEXT) VALUES (NEWS_seq.NEXTVAL,'[新進店家]亞尼克果子工房 十月萬聖搞鬼有禮鑽石','亞尼克果子工房
十月萬聖搞鬼有禮鑽石
各位親愛的主購:
萬聖活動下單時間倒數3天,敬請把握時間~謝謝');

INSERT INTO NEWS(NEWSNO,TITLE,TEXT) VALUES (NEWS_seq.NEXTVAL,'[系統公告]維修時間','各位會員們：
明日上午9點至中午12點系統維修');

INSERT INTO NEWS(NEWSNO,TITLE,TEXT) VALUES (NEWS_seq.NEXTVAL,'[系統公告]輪播廣告功能已上線','各位會員們：
輪播廣告功能上線囉');

INSERT INTO NEWS(NEWSNO,TITLE,TEXT) VALUES (NEWS_seq.NEXTVAL,'冬季感恩回饋','各位主購們：
又到了十月感恩回饋的時刻，今年我們特地新增了12包快速成團，運費只需100元!
薑母鍋 原價100元 特價90元
九尾鍋 原價100元 特價90元
紅燒鍋 原價120元 特價110元
');

INSERT INTO NEWS(NEWSNO,TITLE,TEXT) VALUES (NEWS_seq.NEXTVAL,'試吃推廣活動~真實料多、味美、麵Q彈~高評價義大利麵',
'敝店是以沙拉油、安佳奶油及自煉鴨油做為調理食用油，敬請安心食用~
新增提供銅板價義大利麵醬料包~真的有料~系列
敝店醬汁的濃郁與麵條的Q彈都有再做過調整~歡迎嚐鮮惠顧~
即日起試吃推廣活動~真實料多、味美、麵Q彈~高評價義大利麵
~6份以上義大利麵整組(醬含麵)一律免運費
~12份以上醬料包(不含麵)一律免運費
以上推廣活動(店家保留活動終止日權)
下單後店家會刪除運費~並麻煩先與店家確定到貨日~感謝^^
');

INSERT INTO NEWS(NEWSNO,TITLE,TEXT) VALUES (NEWS_seq.NEXTVAL,'萬聖節狂歡派對開跑!不降價就搗蛋!買到賺到!','萬聖節狂歡派對全店3%回饋金喔~');

INSERT INTO NEWS(NEWSNO,TITLE,TEXT) VALUES (NEWS_seq.NEXTVAL,'[新進店家]亞尼克果子工房 十月萬聖搞鬼有禮鑽石','亞尼克果子工房
十月萬聖搞鬼有禮鑽石
各位親愛的主購:
萬聖活動下單時間倒數3天,敬請把握時間~謝謝');

INSERT INTO NEWS(NEWSNO,TITLE,TEXT) VALUES (NEWS_seq.NEXTVAL,'[系統公告]維修時間','各位會員們：
明日上午9點至中午12點系統維修');

INSERT INTO NEWS(NEWSNO,TITLE,TEXT) VALUES (NEWS_seq.NEXTVAL,'[系統公告]輪播廣告功能已上線','各位會員們：
輪播廣告功能上線囉');

INSERT INTO NEWS(NEWSNO,TITLE,TEXT) VALUES (NEWS_seq.NEXTVAL,'冬季感恩回饋','各位主購們：
又到了十月感恩回饋的時刻，今年我們特地新增了12包快速成團，運費只需100元!
薑母鍋 原價100元 特價90元
九尾鍋 原價100元 特價90元
紅燒鍋 原價120元 特價110元
');

INSERT INTO NEWS(NEWSNO,TITLE,TEXT) VALUES (NEWS_seq.NEXTVAL,'試吃推廣活動~真實料多、味美、麵Q彈~高評價義大利麵',
'敝店是以沙拉油、安佳奶油及自煉鴨油做為調理食用油，敬請安心食用~
新增提供銅板價義大利麵醬料包~真的有料~系列
敝店醬汁的濃郁與麵條的Q彈都有再做過調整~歡迎嚐鮮惠顧~
即日起試吃推廣活動~真實料多、味美、麵Q彈~高評價義大利麵
~6份以上義大利麵整組(醬含麵)一律免運費
~12份以上醬料包(不含麵)一律免運費
以上推廣活動(店家保留活動終止日權)
下單後店家會刪除運費~並麻煩先與店家確定到貨日~感謝^^
');

INSERT INTO NEWS(NEWSNO,TITLE,TEXT) VALUES (NEWS_seq.NEXTVAL,'萬聖節狂歡派對開跑!不降價就搗蛋!買到賺到!','萬聖節狂歡派對全店3%回饋金喔~');

INSERT INTO NEWS(NEWSNO,TITLE,TEXT) VALUES (NEWS_seq.NEXTVAL,'[新進店家]亞尼克果子工房 十月萬聖搞鬼有禮鑽石','亞尼克果子工房
十月萬聖搞鬼有禮鑽石
各位親愛的主購:
萬聖活動下單時間倒數3天,敬請把握時間~謝謝');

INSERT INTO NEWS(NEWSNO,TITLE,TEXT) VALUES (NEWS_seq.NEXTVAL,'[系統公告]維修時間','各位會員們：
明日上午9點至中午12點系統維修');

INSERT INTO NEWS(NEWSNO,TITLE,TEXT) VALUES (NEWS_seq.NEXTVAL,'[系統公告]輪播廣告功能已上線','各位會員們：
輪播廣告功能上線囉');

INSERT INTO NEWS(NEWSNO,TITLE,TEXT) VALUES (NEWS_seq.NEXTVAL,'冬季感恩回饋','各位主購們：
又到了十月感恩回饋的時刻，今年我們特地新增了12包快速成團，運費只需100元!
薑母鍋 原價100元 特價90元
九尾鍋 原價100元 特價90元
紅燒鍋 原價120元 特價110元
');

INSERT INTO NEWS(NEWSNO,TITLE,TEXT) VALUES (NEWS_seq.NEXTVAL,'試吃推廣活動~真實料多、味美、麵Q彈~高評價義大利麵',
'敝店是以沙拉油、安佳奶油及自煉鴨油做為調理食用油，敬請安心食用~
新增提供銅板價義大利麵醬料包~真的有料~系列
敝店醬汁的濃郁與麵條的Q彈都有再做過調整~歡迎嚐鮮惠顧~
即日起試吃推廣活動~真實料多、味美、麵Q彈~高評價義大利麵
~6份以上義大利麵整組(醬含麵)一律免運費
~12份以上醬料包(不含麵)一律免運費
以上推廣活動(店家保留活動終止日權)
下單後店家會刪除運費~並麻煩先與店家確定到貨日~感謝^^
');

INSERT INTO NEWS(NEWSNO,TITLE,TEXT) VALUES (NEWS_seq.NEXTVAL,'萬聖節狂歡派對開跑!不降價就搗蛋!買到賺到!','萬聖節狂歡派對全店3%回饋金喔~');

INSERT INTO NEWS(NEWSNO,TITLE,TEXT) VALUES (NEWS_seq.NEXTVAL,'[新進店家]亞尼克果子工房 十月萬聖搞鬼有禮鑽石','亞尼克果子工房
十月萬聖搞鬼有禮鑽石
各位親愛的主購:
萬聖活動下單時間倒數3天,敬請把握時間~謝謝');

INSERT INTO NEWS(NEWSNO,TITLE,TEXT) VALUES (NEWS_seq.NEXTVAL,'[系統公告]維修時間','各位會員們：
明日上午9點至中午12點系統維修');

INSERT INTO NEWS(NEWSNO,TITLE,TEXT) VALUES (NEWS_seq.NEXTVAL,'[系統公告]輪播廣告功能已上線','各位會員們：
輪播廣告功能上線囉');

INSERT INTO NEWS(NEWSNO,TITLE,TEXT) VALUES (NEWS_seq.NEXTVAL,'冬季感恩回饋','各位主購們：
又到了十月感恩回饋的時刻，今年我們特地新增了12包快速成團，運費只需100元!
薑母鍋 原價100元 特價90元
九尾鍋 原價100元 特價90元
紅燒鍋 原價120元 特價110元
');

INSERT INTO NEWS(NEWSNO,TITLE,TEXT) VALUES (NEWS_seq.NEXTVAL,'試吃推廣活動~真實料多、味美、麵Q彈~高評價義大利麵',
'敝店是以沙拉油、安佳奶油及自煉鴨油做為調理食用油，敬請安心食用~
新增提供銅板價義大利麵醬料包~真的有料~系列
敝店醬汁的濃郁與麵條的Q彈都有再做過調整~歡迎嚐鮮惠顧~
即日起試吃推廣活動~真實料多、味美、麵Q彈~高評價義大利麵
~6份以上義大利麵整組(醬含麵)一律免運費
~12份以上醬料包(不含麵)一律免運費
以上推廣活動(店家保留活動終止日權)
下單後店家會刪除運費~並麻煩先與店家確定到貨日~感謝^^
');

INSERT INTO NEWS(NEWSNO,TITLE,TEXT) VALUES (NEWS_seq.NEXTVAL,'萬聖節狂歡派對開跑!不降價就搗蛋!買到賺到!','萬聖節狂歡派對全店3%回饋金喔~');

INSERT INTO NEWS(NEWSNO,TITLE,TEXT) VALUES (NEWS_seq.NEXTVAL,'[新進店家]亞尼克果子工房 十月萬聖搞鬼有禮鑽石','亞尼克果子工房
十月萬聖搞鬼有禮鑽石
各位親愛的主購:
萬聖活動下單時間倒數3天,敬請把握時間~謝謝');

INSERT INTO NEWS(NEWSNO,TITLE,TEXT) VALUES (NEWS_seq.NEXTVAL,'[系統公告]維修時間','各位會員們：
明日上午9點至中午12點系統維修');

INSERT INTO NEWS(NEWSNO,TITLE,TEXT) VALUES (NEWS_seq.NEXTVAL,'[系統公告]輪播廣告功能已上線','各位會員們：
輪播廣告功能上線囉');



--RunningAd----------------------------------------------------------------
INSERT INTO RUNNINGAD VALUES (runningad_seq.NEXTVAL, null, null, null, null, 1003, TO_DATE('2014-12-03 11:11:00','YYYY-MM-DD HH24:MI:SS'), 0, 3, 5001);
INSERT INTO RUNNINGAD VALUES (runningad_seq.NEXTVAL, null, null, null, null, 1002, TO_DATE('2014-12-03 11:11:00','YYYY-MM-DD HH24:MI:SS'), 0, 5, 5002);
INSERT INTO RUNNINGAD VALUES (runningad_seq.NEXTVAL, null, null, null, null, 1001, TO_DATE('2014-12-03 11:11:00','YYYY-MM-DD HH24:MI:SS'), 0, 5, 5003);
INSERT INTO RUNNINGAD VALUES (runningad_seq.NEXTVAL, null, null, null, null, 1003, TO_DATE('2014-12-04 11:11:00','YYYY-MM-DD HH24:MI:SS'), 0, 3, 5004);
INSERT INTO RUNNINGAD VALUES (runningad_seq.NEXTVAL, null, null, null, null, 1001, TO_DATE('2014-12-04 11:11:00','YYYY-MM-DD HH24:MI:SS'), 0, 6, 5005);
INSERT INTO RUNNINGAD VALUES (runningad_seq.NEXTVAL, null, null, null, null, 1001, TO_DATE('2014-12-04 11:11:00','YYYY-MM-DD HH24:MI:SS'), 0, 2, 5006);
INSERT INTO RUNNINGAD VALUES (runningad_seq.NEXTVAL, null, null, null, null, 1003, TO_DATE('2014-12-05 11:11:00','YYYY-MM-DD HH24:MI:SS'), 0, 3, 5001);
INSERT INTO RUNNINGAD VALUES (runningad_seq.NEXTVAL, null, null, null, null, 1002, TO_DATE('2014-12-05 11:11:00','YYYY-MM-DD HH24:MI:SS'), 0, 4, 5002);
INSERT INTO RUNNINGAD VALUES (runningad_seq.NEXTVAL, null, null, null, null, 1001, TO_DATE('2014-12-05 11:11:00','YYYY-MM-DD HH24:MI:SS'), 0, 6, 5003);
INSERT INTO RUNNINGAD VALUES (runningad_seq.NEXTVAL, null, null, null, null, 1003, TO_DATE('2014-12-05 11:11:00','YYYY-MM-DD HH24:MI:SS'), 0, 1, 5004);


--Update Calculated Data-------------------------------------------------------------
SELECT 'START UPDATE DATA' AS MESSAGE FROM DUAL;

/** update lockflag **//*
UPDATE caseProduct SET lockFlag=1 WHERE cpno in (SELECT UNIQUE cpno FROM cases where status != 0);

/** update member money **//*
UPDATE member SET money = 100;*/

/** update member point **//*
update member set point=0;
update member set point= point+(SELECT SUM(crate) FROM orders WHERE cmemno=1001) where memno=1001;
update member set point= point+(SELECT SUM(brate) FROM orders WHERE bmemno=1001) where memno=1001;
update member set point= point+(SELECT SUM(crate) FROM orders WHERE cmemno=1002) where memno=1002;
update member set point= point+(SELECT SUM(brate) FROM orders WHERE bmemno=1002) where memno=1002;
update member set point= point+(SELECT SUM(crate) FROM orders WHERE cmemno=1003) where memno=1003;
update member set point= point+(SELECT SUM(brate) FROM orders WHERE bmemno=1003) where memno=1003;
update member set point= point+(SELECT SUM(crate) FROM orders WHERE cmemno=1004) where memno=1004;
update member set point= point+(SELECT SUM(brate) FROM orders WHERE bmemno=1004) where memno=1004;
update member set point= point+(SELECT SUM(crate) FROM orders WHERE cmemno=1005) where memno=1005;
update member set point= point+(SELECT SUM(brate) FROM orders WHERE bmemno=1005) where memno=1005;
update member set point= point+(SELECT SUM(crate) FROM orders WHERE cmemno=1006) where memno=1006;
update member set point= point+(SELECT SUM(brate) FROM orders WHERE bmemno=1006) where memno=1006;
update member set point= point+(SELECT SUM(crate) FROM orders WHERE cmemno=1007) where memno=1007;
update member set point= point+(SELECT SUM(brate) FROM orders WHERE bmemno=1007) where memno=1007;
update member set point= point+(SELECT SUM(crate) FROM orders WHERE cmemno=1008) where memno=1008;
update member set point= point+(SELECT SUM(brate) FROM orders WHERE bmemno=1008) where memno=1008;
update member set point= point+(SELECT SUM(crate) FROM orders WHERE cmemno=1009) where memno=1009;
update member set point= point+(SELECT SUM(brate) FROM orders WHERE bmemno=1009) where memno=1009;
update member set point= point+(SELECT SUM(crate) FROM orders WHERE cmemno=1010) where memno=1010;
update member set point= point+(SELECT SUM(brate) FROM orders WHERE bmemno=1010) where memno=1010;
update member set point= point+(SELECT SUM(crate) FROM orders WHERE cmemno=1011) where memno=1011;
update member set point= point+(SELECT SUM(brate) FROM orders WHERE bmemno=1011) where memno=1011;
update member set point= point+(SELECT SUM(crate) FROM orders WHERE cmemno=1012) where memno=1012;
update member set point= point+(SELECT SUM(brate) FROM orders WHERE bmemno=1012) where memno=1012;
update member set point= point+(SELECT SUM(crate) FROM orders WHERE cmemno=1013) where memno=1013;
update member set point= point+(SELECT SUM(brate) FROM orders WHERE bmemno=1013) where memno=1013;
update member set point= point+(SELECT SUM(crate) FROM orders WHERE cmemno=1014) where memno=1014;
update member set point= point+(SELECT SUM(brate) FROM orders WHERE bmemno=1014) where memno=1014;
update member set point= point+(SELECT SUM(crate) FROM orders WHERE cmemno=1015) where memno=1015;
update member set point= point+(SELECT SUM(brate) FROM orders WHERE bmemno=1015) where memno=1015;
update member set point= point+(SELECT SUM(crate) FROM orders WHERE cmemno=1016) where memno=1016;
update member set point= point+(SELECT SUM(brate) FROM orders WHERE bmemno=1016) where memno=1016;
update member set point= point+(SELECT SUM(crate) FROM orders WHERE cmemno=1017) where memno=1017;
update member set point= point+(SELECT SUM(brate) FROM orders WHERE bmemno=1017) where memno=1017;
update member set point= point+(SELECT SUM(crate) FROM orders WHERE cmemno=1018) where memno=1018;
update member set point= point+(SELECT SUM(brate) FROM orders WHERE bmemno=1018) where memno=1018;*/



SELECT 'END UPDATE DATA' AS MESSAGE FROM DUAL;








COMMIT;