DROP TABLE orders;
DROP TABLE WISHLIST;
DROP TABLE caseQA;
DROP TABLE CASEREP;
DROP TABLE cases;
DROP TABLE caseProduct;


DROP TABLE PERLIST;
DROP TABLE PERMISSION;
DROP TABLE ACCOUNT;

DROP TABLE SHOPREP;
DROP TABLE SHOPPRODUCT;
DROP TABLE SHOP;

DROP TABLE RUNNINGAD;

DROP TABLE DPSORD;
DROP TABLE WTDREQ;

DROP TABLE MEMBER;
DROP TABLE LOCATION;
DROP TABLE SUBCATEGORY;
DROP TABLE CATEGORY;

DROP TABLE NEWS;
--SEQUENCES----------------------------------------
DROP SEQUENCE CATEGORY_seq;
DROP SEQUENCE SUBCATEGORY_seq;
DROP SEQUENCE PERMISSION_seq;
--
DROP SEQUENCE shoprep_seq;
DROP SEQUENCE SHOPPRODUCT_seq;
DROP SEQUENCE SHOP_seq;


DROP SEQUENCE member_seq;
DROP SEQUENCE location_seq;
DROP SEQUENCE runningad_seq;

DROP SEQUENCE dpsord_seq;
DROP SEQUENCE wtdreq_seq;
DROP SEQUENCE caserep_seq;
DROP SEQUENCE wishlist_seq;


DROP SEQUENCE caseProduct_seq;
DROP SEQUENCE cases_seq;

DROP SEQUENCE orders_seq;
DROP SEQUENCE caseQA_seq;

DROP SEQUENCE NEWS_SEQ;

commit;